from pyspark.sql.types import (
    BooleanType,
    DateType,
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

from data_platform.data_model import StaticTableModel, TableIdentifier
from data_platform.data_model.metadata_common import standard_columns, standard_tags

contractexportsview = StaticTableModel(
    identifier=TableIdentifier(
        catalog="silver",
        schema="elviz_no",
        name="contract_exports",
    ),
    schema=StructType(
        [
            StructField("contract_export_id", IntegerType(), True, {"comment": "A unique identifier of the exported contract record"}),
            StructField("contract_id", IntegerType(), True, {"comment": "A unique identifier of the contract in the source system"}),
            StructField("auction_type", StringType(), True, {"comment": "Auction mechanism or tender type under which the contract was executed"}),
            StructField("audited", BooleanType(), True, {"comment": "Flag that indicates whether the trade is audited or not"}),
            StructField("authorized", BooleanType(), True, {"comment": "Flag that indicates whether the trade is authorized or not"}),
            StructField("balance_area", StringType(), True, {"comment": "The balancing area of the delivery"}),
            StructField("base_currency", StringType(), True, {"comment": "The base currency "}),
            StructField("broker_company_external_id", StringType(), True, {"comment": "The external system identifier for the broker company"}),
            StructField("broker_company_export_id", IntegerType(), True, {"comment": "The export identifier for the broker company"}),
            StructField("broker_company_id", IntegerType(), True, {"comment": "The identifier for the broker company"}),
            StructField("broker_company_name", StringType(), True, {"comment": "The name of the broker company"}),
            StructField("broker_fee_fixed", DoubleType(), True, {"comment": "The fixed broker fee"}),
            StructField("broker_fee_fixed_unit", StringType(), True, {"comment": "The unit of the fixed broker fee"}),
            StructField("broker_fee_variable", DoubleType(), True, {"comment": "The variable broker fee"}),
            StructField("broker_fee_variable_unit", StringType(), True, {"comment": "The unit of the variable broker fee"}),
            StructField("production_facility_country", StringType(), True, {"comment": "The country of the associated production facility"}),
            StructField("buyer_initiator_aggressor", StringType(), True, {"comment": "Indicates whether the buyer is an initiator or an aggressor"}),
            StructField("buy_sell", StringType(), True, {"comment": "direction of the trade (Buy or Sell)"}),
            StructField("capacity_id", StringType(), True, {"comment": "Identifier of the associated capacity position"}),
            StructField("capacity_bid_price", DoubleType(), True, {"comment": "Bid price submitted for capacity"}),
            StructField("capacity_bid_volume", DoubleType(), True, {"comment": "Bid volume submitted for capacity"}),
            StructField("capacity_traded_volume", DoubleType(), True, {"comment": "Actual traded capacity volume"}),
            StructField("cap_floor_pricing_resolution", StringType(), True, {"comment": "Pricin gresolution for cap/floor structures"}),
            StructField("cash_flow_paid_received", StringType(), True, {"comment": "Indicates of cash flow direction (Paid or Received)"}),
            StructField("certificate_type", StringType(), True, {"comment": "Type of certificate e.g. LECs, VER"}),
            StructField("clearing_fee_fixed", DoubleType(), True, {"comment": "The fixed clearing fee"}),
            StructField("clearing_fee_fixed_unit", StringType(), True, {"comment": "The unit of the fixed clearing fee"}),
            StructField("clearing_fee_variable", DoubleType(), True, {"comment": "The variable clearing fee"}),
            StructField("clearing_fee_variable_unit", StringType(), True, {"comment": "The unit of the variable clearing fee"}),
            StructField("clearing_type", StringType(), True, {"comment": "Type of clearing e.g. Electronic, Broker"}),
            StructField("comment", StringType(), True, {"comment": "Free-text comment"}),
            StructField("commission_fee_fixed", DoubleType(), True, {"comment": "The fixed commission fee"}),
            StructField("commission_fee_fixed_unit", StringType(), True, {"comment": "The unit of the fixed commission fee"}),
            StructField("commission_fee_variable", DoubleType(), True, {"comment": "The variable commission fee"}),
            StructField("commission_fee_variable_unit", StringType(), True, {"comment": "The unit of the variable commission fee"}),
            standard_columns.CommodityColumn.to_struct_field(),
            StructField("company_external_id", StringType(), True, {"comment": "The external system identifier for the company"}),
            StructField("company_export_id", IntegerType(), True, {"comment": "The export identifier for the company"}),
            StructField("company_id", IntegerType(), True, {"comment": "The identifier for the company"}),
            StructField("company_name", StringType(), True, {"comment": "The name of the company"}),
            StructField("confirmed_by_broker", BooleanType(), True, {"comment": "Flag that indicates whether the trade is confirmed by the broker"}),
            StructField("confirmed_by_counterparty", BooleanType(), True, {"comment": "Flag that indicates whether the trade is confirmed by the counterparty"}),
            StructField("contract_model_type", StringType(), True, {"comment": "The model type of the contract e.g. Generation, Retail"}),
            StructField("contract_price_type", StringType(), True, {"comment": "The price type of the contract e.g. Fixed, Spot w/margin"}),
            StructField("contract_time_zone", StringType(), True, {"comment": "The time zone of the contract"}),
            StructField("contract_value", DoubleType(), True, {"comment": "The monetary value of the contract"}),
            StructField("counterparty_company_external_id", StringType(), True, {"comment": "The external system identifier for the counterparty company"}),
            StructField("counterparty_company_export_id", IntegerType(), True, {"comment": "The export identifier for the counterparty company"}),
            StructField("counterparty_company_id", IntegerType(), True, {"comment": "The identifier for the counterparty company"}),
            StructField("counterparty_company_name", StringType(), True, {"comment": "The name of the counterparty company"}),
            StructField("counterparty_portfolio_external_id", StringType(), True, {"comment": "The external system identifier for the counterparty portforlio"}),
            StructField("counterparty_portfolio_export_id", IntegerType(), True, {"comment": "The export identifier for the counterparty portfolio"}),
            StructField("counterparty_portfolio_id", IntegerType(), True, {"comment": "The identifier for the counterparty portforlio"}),
            StructField("counterparty_portfolio_name", StringType(), True, {"comment": "The name of the counterparty portforlio"}),
            StructField("cross_currency", StringType(), True, {"comment": "The cross currency"}),
            StructField("currency", StringType(), True, {"comment": "The currency in the contract"}),
            StructField("currency_source", StringType(), True, {"comment": "The source system"}),
            StructField("deal_compression", BooleanType(), True, {"comment": "Flag that indicates whether the trade is a result of compression"}),
            StructField("deliveries", IntegerType(), True, {"comment": "Delivery schedule definition"}),
            StructField("delivery_location", StringType(), True, {"comment": "Physical or virtual delivery point"}),
            StructField("distributed_quantity", DoubleType(), True, {"comment": "Quantity distributed across sub-positions"}),
            StructField("emir_status", StringType(), True, {"comment": "European Market Infrastructure Regulation (EMIR) reporting status"}),
            StructField("energy_source", StringType(), True, {"comment": "Source of energy e.g. Wind, Solar"}),
            StructField("entry_fee_fixed", DoubleType(), True, {"comment": "The fixed entry fee"}),
            StructField("entry_fee_fixed_unit", StringType(), True, {"comment": "The unit of the fixed entry fee"}),
            StructField("entry_fee_variable", DoubleType(), True, {"comment": "The variable entry fee"}),
            StructField("entry_fee_variable_unit", StringType(), True, {"comment": "The unit of the variable entry fee"}),
            StructField("environment_label", StringType(), True, {"comment": "The environmental classification e.g. Wind, Hydro"}),
            StructField("execution_venue", StringType(), True, {"comment": "Venue on which the trade executed"}),
            StructField("exit_fee_fixed", DoubleType(), True, {"comment": "The fixed exit fee"}),
            StructField("exit_fee_fixed_unit", StringType(), True, {"comment": "The unit of the fixed exit fee"}),
            StructField("exit_fee_variable", DoubleType(), True, {"comment": "The variable exit fee"}),
            StructField("exit_fee_variable_unit", StringType(), True, {"comment": "The unit of the variable exit fee"}),
            StructField("expiry_date", TimestampType(), True, {"comment": "The expiry date of the contract"}),
            StructField("external_id", StringType(), True, {"comment": "The external system identifier for the contract"}),
            StructField("external_source", StringType(), True, {"comment": "The source system name"}),
            StructField("from_country", StringType(), True, {"comment": "The origin country of the delivery"}),
            StructField("from_date", TimestampType(), True, {"comment": "The start date of the contract"}),
            StructField("group_field_1", StringType(), True, {"comment": "Grouping metadata field 1"}),
            StructField("group_field_2", StringType(), True, {"comment": "Grouping metadata field 2"}),
            StructField("group_field_3", StringType(), True, {"comment": "Grouping metadata field 3"}),
            StructField("historic_contract_price_series", StringType(), True, {"comment": "Reference to historical contract price series"}),
            StructField("historic_market_price_series", StringType(), True, {"comment": "Reference to historical market price series"}),
            StructField("index_name", StringType(), True, {"comment": "Name of indexing market"}),
            StructField("initial_price", DoubleType(), True, {"comment": "Initial contract price"}),
            StructField("instrument_name", StringType(), True, {"comment": "Name of the traded instrument"}),
            StructField("instrument_type", StringType(), True, {"comment": "Type of the traded instrument"}),
            StructField("interconnector", StringType(), True, {"comment": "Type of the traded instrument"}),
            StructField("is_originator", BooleanType(), True, {"comment": "Flag that indicates whether entity originated the trade"}),
            StructField("last_updated_time_utc", TimestampType(), True, {"comment": "Last update timestamp in UTC"}),
            StructField("load_profile", StringType(), True, {"comment": "Load of the energy delivery"}),
            StructField("lower_strike", DoubleType(), True, {"comment": "Lower strike price"}),
            StructField("market_price_multiplier", DoubleType(), True, {"comment": "Multiplier applied to the price"}),
            StructField("master_agreement", StringType(), True, {"comment": "Legal master agreement"}),
            StructField("max_volume", DoubleType(), True, {"comment": "Maximum allowed contract volume"}),
            StructField("min_volume", DoubleType(), True, {"comment": "Minimum allowed contract volume"}),
            StructField("original_quantity", DoubleType(), True, {"comment": "The original contracted quantity"}),
            StructField("paid", BooleanType(), True, {"comment": "Flag that indicates whether the payment is paid or not"}),
            StructField("portfolio_external_id", StringType(), True, {"comment": "The external identifier for the portfolio"}),
            StructField("portfolio_export_id", IntegerType(), True, {"comment": "The export identifier for the portfolio"}),
            StructField("portfolio_id", IntegerType(), True, {"comment": "The identifier for the portfolio"}),
            StructField("portfolio_name", StringType(), True, {"comment": "The name of the portfolio"}),
            StructField("price", DoubleType(), True, {"comment": "Contract price"}),
            StructField("price_basis", StringType(), True, {"comment": "Basis used for pricing"}),
            StructField("price_volume_unit", StringType(), True, {"comment": "The unit of the contract price"}),
            StructField("priority", StringType(), True, {"comment": "Transaction priority"}),
            StructField("production_facility", StringType(), True, {"comment": "Associated production facility name"}),
            StructField("put_call", StringType(), True, {"comment": "Option type (Put or Call)"}),
            StructField("quantity", DoubleType(), True, {"comment": "Contract quantity"}),
            StructField("quantity_dependency_reference_contract_export_id", IntegerType(), True, {"comment": "The export identifier for the reference"}),
            StructField("quantity_dependency_reference_contract_id", IntegerType(), True, {"comment": "The identifier for the contract reference"}),
            StructField("quantity_dependency_reference_external_id", StringType(), True, {"comment": "The external identifier for the contract reference"}),
            StructField("quantity_unit", StringType(), True, {"comment": "The unit of the quantity"}),
            StructField("quota_region", StringType(), True, {"comment": "The region of the quota"}),
            StructField("referring_export_id", IntegerType(), True, {"comment": "The reference export identifier"}),
            StructField("remit_reporting", BooleanType(), True, {"comment": "Regulation on Wholesale Energy Market Integrity and Transparency (REMIT) reporting"}),
            StructField("replication_id", StringType(), True, {"comment": "The identifier used for replication or synchronization processes"}),
            StructField("resolution", StringType(), True, {"comment": "Resolution of the contract"}),
            StructField("risk_value", DoubleType(), True, {"comment": "Risk metric associated with trade"}),
            StructField("sampling_from_date", TimestampType(), True, {"comment": "Start date of the sampling period"}),
            StructField("sampling_period", StringType(), True, {"comment": "Duration of sampling"}),
            StructField("sampling_to_date", TimestampType(), True, {"comment": "End date of the sampling period"}),
            StructField("seller_initiator_aggressor", StringType(), True, {"comment": "Indicates whether the seller is an initiator or an aggressor"}),
            StructField("settlement_rule", StringType(), True, {"comment": "Settlement rule applied e.g. EFET"}),
            StructField("settlement_type", StringType(), True, {"comment": "Settlement type e.g. Physical, Financial"}),
            StructField("status", StringType(), True, {"comment": "Contract status"}),
            StructField("strike", DoubleType(), True, {"comment": "Strike price"}),
            StructField("strike_currency", StringType(), True, {"comment": "Currency of strike price"}),
            StructField("strip_expiry_offset", IntegerType(), True, {"comment": "Offset for strip expiry date"}),
            StructField("strip_expiry_time_of_day", TimestampType(), True, {"comment": "Time of day of strip expiry"}),
            StructField("termination_date", DateType(), True, {"comment": "Date of early termination"}),
            StructField("ticket_number", StringType(), True, {"comment": "The source system ticket number"}),
            StructField("time_stamp_authorised_transaction_utc", TimestampType(), True, {"comment": "Timestamp of authorized transaction"}),
            StructField("time_stamp_cleared_utc", TimestampType(), True, {"comment": "Timestamp when trade was cleared"}),
            StructField("time_stamp_confirmation_broker_utc", TimestampType(), True, {"comment": "Timestamp of broker confirmation"}),
            StructField("time_stamp_confirmation_counter_party_utc", TimestampType(), True, {"comment": "Timestamp of broker confirmation"}),
            StructField("time_stamp_counter_party_deal_authorised_utc", TimestampType(), True, {"comment": "Timestamp ocounterparty deal authorization"}),
            StructField("time_stamp_authorised_deal_utc", TimestampType(), True, {"comment": "Timestamp of authorised deal"}),
            StructField("to_country", StringType(), True, {"comment": "The destination country of the delivery"}),
            StructField("to_date", TimestampType(), True, {"comment": "The end date of the contract"}),
            StructField("to_price_basis", StringType(), True, {"comment": "Price basis for deistination market"}),
            StructField("total_volume", DoubleType(), True, {"comment": "Total contracted volume"}),
            StructField("total_volume_unit", StringType(), True, {"comment": "The unit of the total volume"}),
            StructField("user_name", StringType(), True, {"comment": "User name who created the entry"}),
            StructField("trade_date", TimestampType(), True, {"comment": "The date of trade execution"}),
            StructField("trade_date_time", TimestampType(), True, {"comment": "Datetime of trade execution"}),
            StructField("trade_date_time_utc", TimestampType(), True, {"comment": "Datetime of trade execution in UTC"}),
            StructField("trader", StringType(), True, {"comment": "The responsible trader"}),
            StructField("trading_fee_fixed", DoubleType(), True, {"comment": "The fixed trading fee"}),
            StructField("trading_fee_fixed_unit", StringType(), True, {"comment": "The unit of the fixed trading fee"}),
            StructField("trading_fee_variable", DoubleType(), True, {"comment": "The variable trading fee"}),
            StructField("trading_fee_variable_unit", StringType(), True, {"comment": "The unit of the variable trading fee"}),
            StructField("transfer_date", TimestampType(), True, {"comment": "Date of position transfer"}),
            StructField("underlying_instrument_type", StringType(), True, {"comment": "Type of underlying instrument"}),
            StructField("underlying_settlement_type", StringType(), True, {"comment": "Type of underlying settlement"}),
            StructField("underlying_venue", StringType(), True, {"comment": "Venue of underlying instrument"}),
            StructField("upper_strike", DoubleType(), True, {"comment": "Upper strike price for structured trades"}),
            StructField("user_specified_deal_name", StringType(), True, {"comment": "User-specified custom deal name"}),
            StructField("uti", StringType(), True, {"comment": "The unique trade identifier used for regulatory reporting"}),
            StructField("counterparty_trader", StringType(), True, {"comment": "Trader representing counterparty"}),
            StructField("reference_price_series", StringType(), True, {"comment": "The reference price series used"}),
            StructField("destination_reference_price_series", StringType(), True, {"comment": "The destination reference price series used"}),
            StructField("portfolio_parent_id", IntegerType(), True, {"comment": "Parent portfolio identifier"}),
            StructField("portfolio_parent_name", StringType(), True, {"comment": "The name of the parent portfolio"}),
            StructField("counterparty_portfolio_parent_id", IntegerType(), True, {"comment": "Parent counterparty portfolio identifier"}),
            StructField("counterparty_portfolio_parent_name", StringType(), True, {"comment": "The name of the parent counterparty portfolio"}),
            StructField("loss_factor", DoubleType(), True, {"comment": "Loss factor applied to the delivery"}),
            StructField("custom_company_id", StringType(), True, {"comment": "Custom-defined company identifier"}),
            StructField("custom_company_name", StringType(), True, {"comment": "Custom-defined company name"}),
            StructField("technology", StringType(), True, {"comment": "Technology of production e.g. Wind Solar"}),
            StructField("forecast_profile", StringType(), True, {"comment": "Forecasted delivery profile e.g. Monthly Base"}),
            StructField("production_location", StringType(), True, {"comment": "Physical generation or production site"}),
            StructField("authorised_transaction", BooleanType(), True, {"comment": "Flag that indicates whether the transaction is authorized or not"}),
            StructField("authorised_deal", BooleanType(), True, {"comment": "Flag that indicates whether the deal is authorized or not"}),
            StructField("authorised_transaction_by", StringType(), True, {"comment": "User authorizing the transaction"}),
            StructField("authorised_deal_by", StringType(), True, {"comment": "User authorizing the deal"}),
            StructField("audited_by", StringType(), True, {"comment": "User performing audit"}),
            StructField("time_stamp_audited_utc", TimestampType(), True, {"comment": "Timestamp of audit"}),
            standard_columns.LicenseColumn.to_struct_field(),
        ]
    ),
    comment="This table is a reproduction of the ContractExportsView from the Elviz Nordics database.",
    sources=(TableIdentifier(catalog="bronze", schema="elviz_no", name="contractexportsview"),),
    primary_keys=("contract_export_id",),
    tags={
        standard_tags.ConfidentialityLevel.KEY: standard_tags.ConfidentialityLevel.C2_INTERNAL,
        standard_tags.DataDomain.KEY: standard_tags.DataDomain.CONTRACT,
        standard_tags.DataOwner.KEY: standard_tags.DataOwner.PER_SIVERSEN,
        standard_tags.LicensedData.KEY: standard_tags.LicensedData.TRUE,
        standard_tags.PIIClassification.KEY: standard_tags.PIIClassification.NO_PII,
    },
)
