from pyspark.sql.types import LongType, StringType, StructField, StructType

from data_platform.data_model import FileVolumeIdentifier, StaticTableModel, TableIdentifier

ecmwf_ens_forecast_table = StaticTableModel(
    identifier=TableIdentifier("bronze", "meteologica", "ecmwf_ens_forecast"),
    schema=StructType(
        [
            StructField("from_datetime", StringType(), True),
            StructField("to_datetime", StringType(), True),
            StructField("utc_offset_from", StringType(), True),
            StructField("utc_offset_to", StringType(), True),
            StructField("average", StringType(), True),
            StructField("bottom", StringType(), True),
            StructField("top", StringType(), True),
            StructField("ens00", StringType(), True),
            StructField("ens01", StringType(), True),
            StructField("ens02", StringType(), True),
            StructField("ens03", StringType(), True),
            StructField("ens04", StringType(), True),
            StructField("ens05", StringType(), True),
            StructField("ens06", StringType(), True),
            StructField("ens07", StringType(), True),
            StructField("ens08", StringType(), True),
            StructField("ens09", StringType(), True),
            StructField("ens10", StringType(), True),
            StructField("ens11", StringType(), True),
            StructField("ens12", StringType(), True),
            StructField("ens13", StringType(), True),
            StructField("ens14", StringType(), True),
            StructField("ens15", StringType(), True),
            StructField("ens16", StringType(), True),
            StructField("ens17", StringType(), True),
            StructField("ens18", StringType(), True),
            StructField("ens19", StringType(), True),
            StructField("ens20", StringType(), True),
            StructField("ens21", StringType(), True),
            StructField("ens22", StringType(), True),
            StructField("ens23", StringType(), True),
            StructField("ens24", StringType(), True),
            StructField("ens25", StringType(), True),
            StructField("ens26", StringType(), True),
            StructField("ens27", StringType(), True),
            StructField("ens28", StringType(), True),
            StructField("ens29", StringType(), True),
            StructField("ens30", StringType(), True),
            StructField("ens31", StringType(), True),
            StructField("ens32", StringType(), True),
            StructField("ens33", StringType(), True),
            StructField("ens34", StringType(), True),
            StructField("ens35", StringType(), True),
            StructField("ens36", StringType(), True),
            StructField("ens37", StringType(), True),
            StructField("ens38", StringType(), True),
            StructField("ens39", StringType(), True),
            StructField("ens40", StringType(), True),
            StructField("ens41", StringType(), True),
            StructField("ens42", StringType(), True),
            StructField("ens43", StringType(), True),
            StructField("ens44", StringType(), True),
            StructField("ens45", StringType(), True),
            StructField("ens46", StringType(), True),
            StructField("ens47", StringType(), True),
            StructField("ens48", StringType(), True),
            StructField("ens49", StringType(), True),
            StructField("ens50", StringType(), True),
            StructField("content_id", LongType(), True),
            StructField("content_name", StringType(), True),
            StructField("installed_capacity", StringType(), True),
            StructField("issue_date", StringType(), True),
            StructField("timezone", StringType(), True),
            StructField("unit", StringType(), True),
            StructField("update_id", StringType(), True),
        ]
    ),
    primary_keys=("update_id", "issue_date", "content_id", "from_datetime", "to_datetime"),
    sources=[FileVolumeIdentifier("staging", "meteologica", f"meteologica/{id}") for id in ["362", "440", "566"]],
)
