from __future__ import annotations

from pyspark.sql.types import StringType, StructField, StructType

from data_platform.data_model import StaticTableModel, TableIdentifier
from data_platform.data_model.metadata_common import standard_columns, standard_tags

attribute_table = StaticTableModel(
    identifier=TableIdentifier(catalog="silver", schema="mds", name="attribute"),
    schema=StructType([
        StructField("mdo_id", StringType(), True, {"comment": "A unique identifier of the market data object (MDO) in MDS"}),
        StructField("mdo_name", StringType(), True, {"comment": "The name of the market data object (MDO)"}),
        StructField("mdo_source", StringType(), True, {"comment": "The source which defines the market data object (MDO) structure and reference data"}),
        StructField("characteristic", StringType(), True, {"comment": "Identifies the nature of the data points e.g. forecast, measurement"}),
        StructField("resolution", StringType(), True, {"comment": "The granularity or precision of the data e.g. Timestamp, Day"}),
        StructField("resolution_iso", StringType(), True, {"comment": "The time resolution in a standardized ISO 8601 duration format e.g. PT1H"}),
        StructField("timezone", StringType(), True, {"comment": "The timezone in which the data is recorded or referenced e.g. CET, Europe/Berlin"}),
        standard_columns.UnitColumn.to_struct_field(),
        StructField("geolocation", StringType(), True, {"comment": "The geographic location associated with the data"}),
        standard_columns.CommodityColumn.to_struct_field(),
        StructField("technology", StringType(), True, {"comment": "The name of the technology associated with the market data object (MDO)"}),
        StructField("data_type", StringType(), True, {"comment": "The data type of the data e.g. Curve"}),
        standard_columns.LicenseColumn.to_struct_field(),
        standard_columns.DataSourceColumn.to_struct_field(),
        StructField("data_vendor", StringType(), True, {"comment": "The name of the vendor providing the data"}),
        StructField("data_category", StringType(), True, {"comment": "Category of data type defining which API endpoint to request e.g. Curve"}),
        StructField("data_universe", StringType(), True, {"comment": "A collection of market data objects (MDOs) subject to consistant governance and visibility rules"}),
        StructField("data_owner", StringType(), True, {"comment": "The internal department responsible for correctness and/or transparent delivery of data"}),
        StructField("contract_profile", StringType(), True, {"comment": "The detailed characteristics of the contract including delivery pattern, commodity, load shape, etc."}),
        StructField("contract_session", StringType(), True, {"comment": "The trading session of the contract e.g. intraday"}),
        StructField("contract_market_mechanism", StringType(), True, {"comment": "The market mechanism or process through which the contract is traded e.g. Continuoustrading"}),
        StructField("contract_settlement", StringType(), True, {"comment": "The settlement method associated with the contract e.g. financial"}),
        StructField("client_id", StringType(), True, {"comment": "A unique identifier for each client"}),
        StructField("contract", StringType(), True, {"comment": ""}),
        StructField("contract_id", StringType(), True, {"comment": "A unique identifier for each contract"}),
        StructField("criticality", StringType(), True, {"comment": "Represents a numerical ranking from 1 to 9 that indicates the level of importance, urgency, or priority. Each number has a different SLA"}),
        StructField("legacy_cmdp_id", StringType(), True, {"comment": "A unique identifier in Corporate Market Data Pool (CMDP) if the data is migrated from CMDP"}),
        StructField("legacy_cmdp_view_name", StringType(), True, {"comment": "The view name in Corporate Market Data Pool (CMDP) if the data is migrated from CMDP"}),
        StructField("legacy_data_structure", StringType(), True, {"comment": "The data structure in Corporate Market Data Pool (CMDP) if the data is migrated from CMDP"}),
        StructField("model", StringType(), True, {"comment": "The name of the specific model associated with the market data object (MDO)"}),
        StructField("cmdp_column_name", StringType(), True, {"comment": "The column name in Corporate Market Data Pool (CMDP) if the data is migrated from CMDP"}),
        StructField("label", StringType(), True, {"comment": "The label associated with each column"}),
        StructField("column_name", StringType(), True, {"comment": "The name of each column"}),
        StructField("calendar", StringType(), True, {"comment": "The calendar system used for the dataset e.g. Standard Calendar"}),
        StructField("column_type", StringType(), True, {"comment": "Specifies whether the column represents a key or a value in the dataset"}),
        StructField("mesap_id", StringType(), True, {"comment": "A unique identifier in MESAP"}),
        StructField("context", StringType(), True, {"comment": "Provides additional information relevant to the time series"}),
        StructField("contract_type", StringType(), True, {"comment": "The type of the contract e.g. spot"}),
        StructField("contract_period", StringType(), True, {"comment": "The time frame of the contract e.g. Day"}),
        standard_columns.ValidFromColumn.to_struct_field(nullable=True),
        standard_columns.ValidToColumn.to_struct_field(nullable=True),
        standard_columns.IsCurrentColumn.to_struct_field(nullable=True),
        StructField("silver_table", StringType(), True, {"comment": "Contains the table name where the mdo_id is stored in the silver catalog."}),
    ]),
    comment="Attributes (e.g.,license, unit, geolocation, etc.) that are associated with various entities within MDS.",
    sources=[TableIdentifier(catalog="bronze", schema="mds", name="mdo_attributes")],
    primary_keys=("mdo_id", "column_name"),
    tags={
        standard_tags.ConfidentialityLevel.KEY: standard_tags.ConfidentialityLevel.C2_INTERNAL,
        standard_tags.PIIClassification.KEY: standard_tags.PIIClassification.NO_PII,
        standard_tags.DataOwner.KEY: standard_tags.DataOwner.YUFAN_HE,
        standard_tags.LicensedData.KEY: standard_tags.LicensedData.FALSE,
    },
)
