# Databricks notebook source
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

# COMMAND ----------


catalog_prefix = dbutils.widgets.get("env_catalog_identifier")  # type: ignore # noqa: F821
schema_prefix = dbutils.widgets.get("schema_prefix")  # type: ignore # noqa: F821
schema = "data_quality"
table = "data_quality_metrics"
full_table_name = f"{catalog_prefix}gold.{schema_prefix}{schema}.{table}"
dq_rules_schema = (
    "schema string NOT NULL, "
    "table string NOT NULL, "
    "name string NOT NULL, "
    "evaluation string NOT NULL, "
    "passing_records bigint, "
    "failing_records bigint, "
    "total_number_of_records bigint, "
    "`timestamp` timestamp, "
    "created_at timestamp, "
    "created_by string, "
    "updated_at timestamp, "
    "updated_by string, "
    "table_id BIGINT not null GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)"
)

query_to_populate = f"""(
    select
        dataset as schema,
        source_table as table,
        expectation as name,
        concat(
        date_format(`timestamp`, "yyyyMMdd"),
                "_",
                date_format(`timestamp`, "HHmm")
        )
        as evaluation,
        passing_records,
        failing_records,
        total_number_of_records,
        `timestamp`,
        created_at,
        created_by,
        updated_at
        from {full_table_name}_backup
)"""


spark.sql(f"ALTER TABLE {full_table_name} DROP CONSTRAINT IF EXISTS pk_{table}")
spark.sql(f"ALTER TABLE {full_table_name} RENAME TO {full_table_name}_backup")

spark.sql(f"CREATE TABLE IF NOT EXISTS {full_table_name} ({dq_rules_schema})")

try:
    spark.sql(f"ALTER TABLE {full_table_name} ADD CONSTRAINT pk_{table} PRIMARY KEY (schema, table, name, evaluation)")
    df_to_populate = spark.sql(query_to_populate)
    df_to_populate.write.format("delta").mode("append").saveAsTable(full_table_name)
    spark.sql(f"DROP TABLE IF EXISTS {full_table_name}_backup")
except Exception as e:
    print(f"Error while populating {full_table_name}: {e}")
