from pyspark.sql.types import BooleanType, DoubleType, StringType, StructField, StructType, TimestampType

from data_platform.data_model import StaticTableModel, TableIdentifier

contract_table = StaticTableModel(
    identifier=TableIdentifier(
        catalog="bronze",
        schema="neuron",
        name="falcon_contract",
    ),
    schema=StructType(
        [
            StructField("ID_CONTRACT", StringType(), True, {}),
            StructField("CUPS", StringType(), True, {}),
            StructField(
                "ATR",
                BooleanType(),
                True,
                {},
            ),
            StructField("ACCOUNT_NAME", StringType(), True, {}),
            StructField("ACTIVATED_DATE", StringType(), True, {}),
            StructField("ADVANCE", BooleanType(), True, {}),
            StructField("AMOUNT_FIXED_FEE", DoubleType(), True, {}),
            StructField("ANNUAL_VOLUME", DoubleType(), True, {}),
            StructField("ANUAL_P1_KWH", DoubleType(), True, {}),
            StructField("ANUAL_P2_KWH", DoubleType(), True, {}),
            StructField("ANUAL_P3_KWH", DoubleType(), True, {}),
            StructField("BILL_SHIPPING_METHOD", StringType(), True, {}),
            StructField(
                "BUSINESS_DIVISION",
                StringType(),
                True,
                {},
            ),
            StructField(
                "BUSINESS_LINE",
                StringType(),
                True,
                {},
            ),
            StructField("CRM_COMMISSION", DoubleType(), True, {}),
            StructField("CARD_TYPE", StringType(), True, {}),
            StructField(
                "CANCEL_REASON",
                DoubleType(),
                True,
                {},
            ),
            StructField(
                "DIST_CODE",
                StringType(),
                True,
                {},
            ),
            StructField("AGENT_COMMISSION", DoubleType(), True, {}),
            StructField("BOSS_COMMISSION", DoubleType(), True, {}),
            StructField("SUBAGENT_COMMISSION", DoubleType(), True, {}),
            StructField("CONTRACT_CODE", StringType(), True, {}),
            StructField("CONTRACT_CODE_2", StringType(), True, {}),
            StructField("CONTRACT_CODE_FINAL", StringType(), True, {}),
            StructField("COUNTER_PARTY", StringType(), True, {}),
            StructField("CUSTOMER_SIGNED_DATE", StringType(), True, {}),
            StructField("COUNTRY", StringType(), True, {}),
            StructField("TARIFA", StringType(), True, {}),
            StructField("END_CONTRACT", DoubleType(), True, {}),
            StructField("ESTIMATED_START_DATE_CONTRACT", StringType(), True, {}),
            StructField(
                "FECHA_PRICING",
                StringType(),
                True,
                {},
            ),
            StructField(
                "GREEN_PRODUCT",
                BooleanType(),
                True,
                {},
            ),
            StructField("MOTIVO_BAJA", DoubleType(), True, {}),
            StructField("PRODUCT_NAME", StringType(), True, {}),
            StructField("START_DATE", StringType(), True, {}),
            StructField("STATE", StringType(), True, {}),
            StructField(
                "STATUS",
                StringType(),
                True,
                {},
            ),
            StructField("CUPS22", StringType(), True, {}),
            StructField(
                "TIMESTAMP_CREATION",
                TimestampType(),
                True,
                {},
            ),
            StructField(
                "TIMESTAMP_UPDATE",
                TimestampType(),
                True,
                {},
            ),
            StructField("P4_ANUAL_KWH", DoubleType(), True, {}),
            StructField("P5_ANUAL_KWH", DoubleType(), True, {}),
            StructField("P6_ANUAL_KWH", DoubleType(), True, {}),
            StructField(
                "CREATED_DATE",
                StringType(),
                True,
                {},
            ),
            StructField("FECHA_FIN_TEORICA_CONTRATO", TimestampType(), True, {}),
            StructField("FECHA_FIN_DEFINITIVA_CONTRATO", TimestampType(), True, {}),
            StructField(
                "SRC_CREATED_BY",
                StringType(),
                True,
                {},
            ),
            StructField(
                "SRC_CREATED_AT",
                TimestampType(),
                True,
                {},
            ),
        ]
    ),
    comment="Iberia retail contract data from Neuron AA system.",
    sources=(TableIdentifier(catalog="neuron_aa_prod", schema="falcon_aws", name="contract"),),
    primary_keys=("ID_CONTRACT",),
    tags={
        "License": "Licence",
        "Confidentiality Level": "C2_Internal",
        "Personal sensitive information": "No PII",
        "Source System": "Neuron",
        "LPI": "Falcon_AXPO-IBERIA_Neuron",
        "Data Owner": "Ignacio Ortiz de Zuniga",
    },
)
