from pyspark.sql.types import BooleanType, DecimalType, DoubleType, StringType, StructField, StructType, TimestampType

from data_platform.data_model import StaticTableModel, TableIdentifier

product_contract_table = StaticTableModel(
    identifier=TableIdentifier(
        catalog="bronze",
        schema="neuron",
        name="falcon_product_contract",
    ),
    schema=StructType(
        [
            StructField("CUPS", StringType(), True, {}),
            StructField("ID_CONTRACT", StringType(), True, {}),
            StructField("OWNER", StringType(), True, {}),
            StructField("ACCOUNTID", StringType(), True, {}),
            StructField("NAME", StringType(), True, {}),
            StructField("ROOTASSET", StringType(), True, {}),
            StructField("POTENCIA_CONTRATADA_P3_KW", DoubleType(), True, {}),
            StructField("PC_ANUAL_P1_KWH", DoubleType(), True, {}),
            StructField("FECHA_FIN_PRODUCTO", StringType(), True, {}),
            StructField("PROGRAMMING_UNIT", StringType(), True, {}),
            StructField("PRODUCT_IS_ARCHIVED", BooleanType(), True, {}),
            StructField("MARKETER", StringType(), True, {}),
            StructField("FECHA_INICIO_PRODUCTO", StringType(), True, {}),
            StructField("TOTALDAILYCONS", DoubleType(), True, {}),
            StructField("ID_PRODUCTO", StringType(), True, {}),
            StructField(
                "IS_COMPETITOR_PRODUCT",
                BooleanType(),
                True,
                {},
            ),
            StructField("CONTRACT_EDQA", DecimalType(38, 0), True, {}),
            StructField("PC_ANUAL_P5_KWH", DoubleType(), True, {}),
            StructField("PC_ANUAL_P3_KWH", DoubleType(), True, {}),
            StructField("STATUS", StringType(), True, {}),
            StructField("PARTNER_MARGIN", DoubleType(), True, {}),
            StructField("PC_ANUAL_P6_KWH", DoubleType(), True, {}),
            StructField("CIF", StringType(), True, {}),
            StructField("ID_PEAJE", StringType(), True, {}),
            StructField("AXPO_MARGIN", DoubleType(), True, {}),
            StructField("PRODUCT_TYPE", StringType(), True, {}),
            StructField("COMMISSIONER", BooleanType(), True, {}),
            StructField("CUPS_PRODUCT", StringType(), True, {}),
            StructField("SETTLEMENT_MODE", StringType(), True, {}),
            StructField("ID_PRECIO_BASE", StringType(), True, {}),
            StructField("QA", DoubleType(), True, {}),
            StructField("POTENCIA_CONTRATADA_P6_KW", DoubleType(), True, {}),
            StructField("CONTRACTED_PRODUCT_CODE_AUX", StringType(), True, {}),
            StructField(
                "PRODUCT_BUSINESS_LINE",
                StringType(),
                True,
                {},
            ),
            StructField("POTENCIA_CONTRATADA_P4_KW", DoubleType(), True, {}),
            StructField("POTENCIA_CONTRATADA_P2_KW", DoubleType(), True, {}),
            StructField("ASSET_VERSION", DecimalType(38, 0), True, {}),
            StructField("TIPO_PRODUCTO", StringType(), True, {}),
            StructField("CONTRACT", StringType(), True, {}),
            StructField("PC_ANUAL_P2_KWH", DoubleType(), True, {}),
            StructField("PC_ANUAL_P4_KWH", DoubleType(), True, {}),
            StructField(
                "SRC_CREATED_BY",
                StringType(),
                True,
                {},
            ),
            StructField(
                "SRC_CREATED_AT",
                TimestampType(),
                True,
                {},
            ),
        ]
    ),
    comment="Product contract data for electricity supply points in the Spanish market (Neuron AA system).",
    sources=(TableIdentifier(catalog="neuron_aa_prod", schema="falcon_aws", name="product_contract"),),
    primary_keys=(
        "ID_CONTRACT",
        "ID_PRODUCTO",
    ),
    tags={
        "License": "Licence",
        "Confidentiality Level": "C2_Internal",
        "Personal sensitive information": "No PII",
        "Source System": "Neuron",
        "LPI": "Falcon_AXPO-IBERIA_Neuron",
        "Data Owner": "Ignacio Ortiz de Zuniga",
    },
)
