from pyspark.sql.types import BooleanType, DateType, DecimalType, StringType, StructField, StructType, TimestampType

from data_platform.data_model import StaticTableModel, TableIdentifier

salesforce_rep_asset_table = StaticTableModel(
    identifier=TableIdentifier(
        catalog="bronze",
        schema="neuron",
        name="salesforce_rep_asset",
    ),
    schema=StructType(
        [
            StructField("ID", StringType(), True, {}),
            StructField("CONTACTID", StringType(), True, {}),
            StructField("ACCOUNTID", StringType(), True, {}),
            StructField(
                "PARENTID",
                StringType(),
                True,
                {},
            ),
            StructField("ROOTASSETID", StringType(), True, {}),
            StructField("PRODUCT2ID", StringType(), True, {}),
            StructField("PRODUCTCODE", StringType(), True, {}),
            StructField("PRODUCTFAMILY", StringType(), True, {}),
            StructField("PRODUCTDESCRIPTION", StringType(), True, {}),
            StructField(
                "ISCOMPETITORPRODUCT",
                BooleanType(),
                True,
                {},
            ),
            StructField("CREATEDDATE", TimestampType(), True, {}),
            StructField("CREATEDBYID", StringType(), True, {}),
            StructField(
                "LASTMODIFIEDDATE",
                TimestampType(),
                True,
                {},
            ),
            StructField("LASTMODIFIEDBYID", StringType(), True, {}),
            StructField("SYSTEMMODSTAMP", TimestampType(), True, {}),
            StructField(
                "ISDELETED",
                BooleanType(),
                True,
                {},
            ),
            StructField("NAME", StringType(), True, {}),
            StructField("SERIALNUMBER", StringType(), True, {}),
            StructField("INSTALLDATE", DateType(), True, {}),
            StructField("MANUFACTUREDATE", DateType(), True, {}),
            StructField("STATUSREASON", StringType(), True, {}),
            StructField("UUID", StringType(), True, {}),
            StructField("EXTERNALIDENTIFIER", StringType(), True, {}),
            StructField("PURCHASEDATE", DateType(), True, {}),
            StructField("USAGEENDDATE", DateType(), True, {}),
            StructField("STATUS", StringType(), True, {}),
            StructField("DIGITALASSETSTATUS", StringType(), True, {}),
            StructField("PRICE", DecimalType(18, 2), True, {}),
            StructField("QUANTITY", DecimalType(12, 2), True, {}),
            StructField("DESCRIPTION", StringType(), True, {}),
            StructField("OWNERID", StringType(), True, {}),
            StructField("RECORDTYPEID", StringType(), True, {}),
            StructField("ASSETPROVIDEDBYID", StringType(), True, {}),
            StructField("ASSETSERVICEDBYID", StringType(), True, {}),
            StructField(
                "ISINTERNAL",
                BooleanType(),
                True,
                {},
            ),
            StructField("ASSETLEVEL", DecimalType(38, 0), True, {}),
            StructField("STOCKKEEPINGUNIT", StringType(), True, {}),
            StructField(
                "CONSEQUENCEOFFAILURE",
                StringType(),
                True,
                {},
            ),
            StructField(
                "EXTERNAL_ID_PRODUCTO_CONTRATADO__C",
                StringType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ANNUALCONS__C",
                DecimalType(18, 2),
                True,
                {},
            ),
            StructField("FALCON_FLD_CUPS__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_COMMERCIALAGREEMENT__C",
                StringType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_COMMISSIONER__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_CONTRACT__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_CONTRACTEDPRODUCTCODE_AUX__C",
                StringType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTEDPRODUCT__C",
                BooleanType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTEDQA__C",
                DecimalType(18, 0),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTEDQD__C",
                DecimalType(18, 0),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTEDQH__C",
                DecimalType(18, 0),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ENDDATEVERSION__C",
                DateType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_IDBASEPRICE__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_MASTERPRODUCT__C",
                StringType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_OILSPECIALTAXTYPE__C",
                StringType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_PARTNERMARGIN__C",
                DecimalType(18, 2),
                True,
                {},
            ),
            StructField("FALCON_FLD_PRICESLEVEL__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_QUOTECUPSAUX__C",
                StringType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_STARTDATEVERSION__C",
                DateType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_SYNCHORNIZED__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_TOLL__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_ASSETVERSION__C",
                DecimalType(10, 0),
                True,
                {},
            ),
            StructField("FALCON_FLD_LASTPC__C", BooleanType(), True, {}),
            StructField(
                "FALCON_FLD_AMORTIZATIONPERIOD__C",
                DecimalType(18, 0),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_AMOUNTEFFICIENCY__C",
                DecimalType(18, 2),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CRMCOMMISSION__C",
                DecimalType(18, 2),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_COLLECTIONUNIT__C",
                StringType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONFORMITYDECLARATIONDATE__C",
                DateType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTPOWERP1__C",
                DecimalType(16, 4),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTPOWERP2__C",
                DecimalType(16, 4),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTPOWERP3__C",
                DecimalType(16, 4),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTPOWERP4__C",
                DecimalType(16, 4),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTPOWERP5__C",
                DecimalType(16, 4),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_CONTRACTPOWERP6__C",
                DecimalType(16, 4),
                True,
                {},
            ),
            StructField("FALCON_FLD_DURATION__C", DecimalType(3, 0), True, {}),
            StructField(
                "FALCON_FLD_EXTRACTIONSCOMPLETED__C",
                DecimalType(18, 0),
                True,
                {},
            ),
            StructField("FALCON_FLD_FINANCINGPERIOD__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_INFLATION__C",
                DecimalType(3, 0),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_INSTALLEDTOTALPOWERFV__C",
                DecimalType(18, 1),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_MILESTONESCOUNT__C",
                DecimalType(18, 0),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_NUMTOTALMILESTONES__C",
                DecimalType(18, 0),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_OPERATIONMAINTENANCECOSTS__C",
                DecimalType(18, 2),
                True,
                {},
            ),
            StructField("FALCON_FLD_PAYMENTTIME__C", StringType(), True, {}),
            StructField("FALCON_FLD_PRICE__C", DecimalType(12, 2), True, {}),
            StructField("FALCON_FLD_PRODUCTNAME__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_QUALITYCONTROLEFFICIENCY__C",
                BooleanType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_AMOUNTEFFICIENCYFV__C",
                DecimalType(18, 2),
                True,
                {},
            ),
            StructField(
                "SRC_CREATED_BY",
                StringType(),
                True,
                {},
            ),
            StructField(
                "SRC_CREATED_AT",
                TimestampType(),
                True,
                {},
            ),
        ]
    ),
    comment="Salesforce asset data for electricity and energy products (bronze layer).",
    sources=(TableIdentifier(catalog="neuron_aa_prod", schema="salesforce_rep", name="asset"),),
    primary_keys=("ID",),
    tags={
        "License": "Licence",
        "Confidentiality Level": "C2_Internal",
        "Personal sensitive information": "No PII",
        "Source System": "Neuron",
        "LPI": "Salesforce_AXPO-IBERIA_Neuron",
        "Data Owner": "Ignacio Ortiz de Zuniga",
    },
)
