from pyspark.sql.types import BooleanType, DecimalType, DoubleType, StringType, StructField, StructType, TimestampType

from data_platform.data_model import StaticTableModel, TableIdentifier

salesforce_rep_contract_table = StaticTableModel(
    identifier=TableIdentifier(
        catalog="bronze",
        schema="neuron",
        name="salesforce_rep_contract",
    ),
    schema=StructType(
        [
            StructField("ID", StringType(), True, {}),
            StructField("ACCOUNTID", StringType(), True, {}),
            StructField("PRICEBOOK2ID", StringType(), True, {}),
            StructField("OWNEREXPIRATIONNOTICE", StringType(), True, {}),
            StructField("STARTDATE", TimestampType(), True, {}),
            StructField("ENDDATE", TimestampType(), True, {}),
            StructField("BILLINGSTREET", StringType(), True, {}),
            StructField("BILLINGCITY", StringType(), True, {}),
            StructField("BILLINGSTATE", StringType(), True, {}),
            StructField("BILLINGPOSTALCODE", StringType(), True, {}),
            StructField("BILLINGCOUNTRY", StringType(), True, {}),
            StructField("BILLINGSTATECODE", StringType(), True, {}),
            StructField("BILLINGCOUNTRYCODE", StringType(), True, {}),
            StructField("BILLINGLATITUDE", DoubleType(), True, {}),
            StructField("BILLINGLONGITUDE", DoubleType(), True, {}),
            StructField("BILLINGGEOCODEACCURACY", StringType(), True, {}),
            StructField("BILLINGADDRESS", StringType(), True, {}),
            StructField("SHIPPINGSTREET", StringType(), True, {}),
            StructField("SHIPPINGCITY", StringType(), True, {}),
            StructField("SHIPPINGSTATE", StringType(), True, {}),
            StructField("SHIPPINGPOSTALCODE", StringType(), True, {}),
            StructField("SHIPPINGCOUNTRY", StringType(), True, {}),
            StructField("SHIPPINGSTATECODE", StringType(), True, {}),
            StructField("SHIPPINGCOUNTRYCODE", StringType(), True, {}),
            StructField("SHIPPINGLATITUDE", DoubleType(), True, {}),
            StructField("SHIPPINGLONGITUDE", DoubleType(), True, {}),
            StructField("SHIPPINGGEOCODEACCURACY", StringType(), True, {}),
            StructField("SHIPPINGADDRESS", StringType(), True, {}),
            StructField("CONTRACTTERM", DecimalType(38, 0), True, {}),
            StructField("OWNERID", StringType(), True, {}),
            StructField("STATUS", StringType(), True, {}),
            StructField("COMPANYSIGNEDID", StringType(), True, {}),
            StructField("COMPANYSIGNEDDATE", TimestampType(), True, {}),
            StructField("CUSTOMERSIGNEDID", StringType(), True, {}),
            StructField("CUSTOMERSIGNEDTITLE", StringType(), True, {}),
            StructField("CUSTOMERSIGNEDDATE", TimestampType(), True, {}),
            StructField("SPECIALTERMS", StringType(), True, {}),
            StructField("ACTIVATEDBYID", StringType(), True, {}),
            StructField("ACTIVATEDDATE", TimestampType(), True, {}),
            StructField("STATUSCODE", StringType(), True, {}),
            StructField("DESCRIPTION", StringType(), True, {}),
            StructField("RECORDTYPEID", StringType(), True, {}),
            StructField("NAME", StringType(), True, {}),
            StructField("ISDELETED", BooleanType(), True, {}),
            StructField("CONTRACTNUMBER", StringType(), True, {}),
            StructField("LASTAPPROVEDDATE", TimestampType(), True, {}),
            StructField("CREATEDDATE", TimestampType(), True, {}),
            StructField("CREATEDBYID", StringType(), True, {}),
            StructField("LASTMODIFIEDDATE", TimestampType(), True, {}),
            StructField("LASTMODIFIEDBYID", StringType(), True, {}),
            StructField("SYSTEMMODSTAMP", TimestampType(), True, {}),
            StructField("LASTACTIVITYDATE", TimestampType(), True, {}),
            StructField("LASTVIEWEDDATE", TimestampType(), True, {}),
            StructField("LASTREFERENCEDDATE", TimestampType(), True, {}),
            StructField("CARD_NUMBER__C", StringType(), True, {}),
            StructField("CARD_TYPE__C", StringType(), True, {}),
            StructField(
                "DATA_QUALITY_DESCRIPTION__C",
                StringType(),
                True,
                {},
            ),
            StructField("DATA_QUALITY_SCORE__C", DoubleType(), True, {}),
            StructField("FALCON_CONTACT__C", StringType(), True, {}),
            StructField("FALCON_FLD_ATR_CODE__C", StringType(), True, {}),
            StructField("FALCON_FLD_ATR__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_ADVANCETYPE__C", StringType(), True, {}),
            StructField("FALCON_FLD_ADVANCE__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_AGENCY_CLIENT__C", StringType(), True, {}),
            StructField("FALCON_FLD_AMOUNTADVANCE__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_AMOUNTFIXEDFEE__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_ANNUALVOLUME__C",
                DoubleType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_ATTENTION__C", StringType(), True, {}),
            StructField("FALCON_FLD_AXPOMARGIN__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_BANKACCOUNT__C", StringType(), True, {}),
            StructField("FALCON_FLD_BILLSHIPPINGMETHOD__C", StringType(), True, {}),
            StructField("FALCON_FLD_BILLINGADDRESS__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_BUNDLEBILLING__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_BUSINESSDIVISION__C", StringType(), True, {}),
            StructField("FALCON_FLD_BUSSINESSLINE__C", StringType(), True, {}),
            StructField("FALCON_FLD_CIFNIF__C", StringType(), True, {}),
            StructField("FALCON_FLD_CUPSADDRESS__C", StringType(), True, {}),
            StructField("FALCON_FLD_CUPSAUX__C", StringType(), True, {}),
            StructField("FALCON_FLD_CUPS__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_COMMERCIALAGREEMENT__C",
                StringType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_CONTRACTCODE2__C", StringType(), True, {}),
            StructField("FALCON_FLD_CONTRACTENTITY__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_CONTRACTTYPE__C", StringType(), True, {}),
            StructField("FALCON_FLD_CONTRACTVERSION__C", StringType(), True, {}),
            StructField("FALCON_FLD_CREATEDDATE__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_CUSTOMERORDERNUM__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_DATECONTRACTRECOVER__C",
                TimestampType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_DOCUMENTURL__C", StringType(), True, {}),
            StructField("FALCON_FLD_DOWNLOAD__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_EARLYCANCELPENALTY__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_ENDCONTRACT__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_ENDDATE_CUSTOM__C", TimestampType(), True, {}),
            StructField(
                "FALCON_FLD_ESTIMATEDENDDATECONTRACT__C",
                TimestampType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ESTIMATEDSTARDATECONTRACT__C",
                TimestampType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_FIXEDFEE__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_FORMALIZED__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_GESTOR__C", StringType(), True, {}),
            StructField("FALCON_FLD_IBANVALUE_FOR__C", StringType(), True, {}),
            StructField("FALCON_FLD_IBAN_FOR__C", StringType(), True, {}),
            StructField("FALCON_FLD_IEH_INDUSTRIALUSE__C", StringType(), True, {}),
            StructField("FALCON_FLD_IEH_USEGENERATION__C", StringType(), True, {}),
            StructField("FALCON_FLD_IEH__C", StringType(), True, {}),
            StructField("FALCON_FLD_IDBASEPRICE__C", StringType(), True, {}),
            StructField("FALCON_FLD_ID_CONTRATC_OLD_CRM__C", StringType(), True, {}),
            StructField("FALCON_FLD_IMPORTED__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_KAM_AGENT__C", StringType(), True, {}),
            StructField("FALCON_FLD_KAM__C", StringType(), True, {}),
            StructField("FALCON_FLD_MARKETER__C", StringType(), True, {}),
            StructField("FALCON_FLD_OLDCONTRACT__C", StringType(), True, {}),
            StructField("FALCON_FLD_MOTIVOBAJA__C", StringType(), True, {}),
            StructField("FALCON_FLD_NEWCONTRACT__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_NEXTRENEWALDATE__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_NO_COMISIONAR__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_PAYMENTMETHOD_FOR__C", StringType(), True, {}),
            StructField("FALCON_FLD_PAYMENTMETHOD__C", StringType(), True, {}),
            StructField("FALCON_FLD_PAYMENTTIMES_FOR__C", StringType(), True, {}),
            StructField("FALCON_FLD_PAYMENTTIMES__C", StringType(), True, {}),
            StructField("FALCON_FLD_PENALTY__C", DoubleType(), True, {}),
            StructField(
                "FALCON_FLD_PHYSICDOCRECEIVED__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_POWER__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_PREVIOUS_ATR_CODE__C", StringType(), True, {}),
            StructField("FALCON_FLD_QUOTENEW__C", StringType(), True, {}),
            StructField("FALCON_FLD_RATE__C", StringType(), True, {}),
            StructField("FALCON_FLD_READYTORENEW__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_REASSIGNED__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_RENEWALCOMPLAINT__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_RENEWED__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_SEPA__C", StringType(), True, {}),
            StructField("FALCON_FLD_SWIFTVALUE__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_SAME_BILLING_CONDITIONS__C",
                BooleanType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_STARTDATEBEFORETODAY__C",
                DoubleType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_STARTDATEBEFORETODAYAND30__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_STARTDATEPENALTY__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_STATE__C", StringType(), True, {}),
            StructField("FALCON_FLD_REFERENCECODE__C", StringType(), True, {}),
            StructField("FALCON_FLD_SYNCHORNIZED__C", BooleanType(), True, {}),
            StructField(
                "FALCON_FLD_SYNCHRONIZATIONERROR__C",
                BooleanType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_RENEWALREQUESTANSWERED__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_TELMED__C", DoubleType(), True, {}),
            StructField("FALCON_OBJ_PLANTILLA__C", StringType(), True, {}),
            StructField("FALCON_FLD_FULLADDRESS__C", StringType(), True, {}),
            StructField("METHOD_OF_PAYMENT__C", StringType(), True, {}),
            StructField("PAPERLESS_BILLING__C", BooleanType(), True, {}),
            StructField("PAYMENT_DAY__C", StringType(), True, {}),
            StructField("FALCON_FLD_ACCOUNTNAME__C", StringType(), True, {}),
            StructField("FALCON_FLD_CONTRACTCODE__C", StringType(), True, {}),
            StructField("FALCON_FLD_CONTRACTCODEFORMULA__C", StringType(), True, {}),
            StructField("FALCON_FLD_AMOUNTADVANCE_NAV__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_FIRSTREP__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_IEH_EXEMPT__C", StringType(), True, {}),
            StructField("FALCON_FLD_NAV_OK__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_WSO2_OK__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_ALLSC__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_ALL_SC_NAV_OK__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_ALL_SC_WSO2_OK__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_EXEMPTPERCENTAGE__C", StringType(), True, {}),
            StructField("FALCON_FLD_PRICESLEVEL__C", StringType(), True, {}),
            StructField("FALCON_FLD_IEH_ENDDATECIE__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_IEH_STARTDATECIE__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_MASTERPARTNER__C", StringType(), True, {}),
            StructField("FALCON_FLD_TEAMMANAGER__C", StringType(), True, {}),
            StructField("FALCON_FLD_SUBPARTNER__C", StringType(), True, {}),
            StructField("FALCON_FLD_COMISION_JEFE_EQUIPO__C", StringType(), True, {}),
            StructField("FALCON_FLD_COMISION_SUBAGENTE__C", StringType(), True, {}),
            StructField("FALCON_FLD_S3_OK__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_ALL_SC_S3_OK__C", DoubleType(), True, {}),
            StructField(
                "FALCON_FLD_COMISION_AGENTE_MASTER__C",
                StringType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_EARLYRESOLUTIONDATE__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_ADVANCETYPE2__C", StringType(), True, {}),
            StructField("FALCON_FLD_NOTRENEW__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_AMOUNTFIXEDFEE_QC__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_CHECKCALLIDUS__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_CONTRACTCODEFINAL__C", StringType(), True, {}),
            StructField("FALCON_FLD_RESPONSIBLECOMPLAINT__C", StringType(), True, {}),
            StructField("FALCON_FLD_REVIEWEDCONTRACT__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_APMCODE__C", StringType(), True, {}),
            StructField("FALCON_FLD_ACTIVEPERIOD__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_BENEFITCIEPERCENT__C", StringType(), True, {}),
            StructField("FALCON_FLD_BRANDMODEL__C", StringType(), True, {}),
            StructField("FALCON_FLD_CIE__C", StringType(), True, {}),
            StructField("FALCON_FLD_CODIGOCIE__C", StringType(), True, {}),
            StructField("FALCON_FLD_CRMCOMMISSION__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_COMMENTS__C", StringType(), True, {}),
            StructField("FALCON_FLD_DEVICEBRAND__C", StringType(), True, {}),
            StructField("FALCON_FLD_DEVICEMODEL__C", StringType(), True, {}),
            StructField("FALCON_FLD_DEVICETYPE__C", StringType(), True, {}),
            StructField("FALCON_FLD_EFFECTIVEDATECIE__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_ELECTRONICSTAMP__C", StringType(), True, {}),
            StructField("FALCON_FLD_EMISSIONDATEAPM__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_EXEMPTIONIEPERCENT__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_EXEMPTIONIETYPE__C", StringType(), True, {}),
            StructField("FALCON_FLD_EXEMPTIONIE__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_EXPIRATIONDATEAPM__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_EXTRACTIONSCOMPLETED__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_FECHAPRICING__C", TimestampType(), True, {}),
            StructField("FALCON_FLD_GREENPRODUCT__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_HASDISCOUNT__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_INSTATPOWER__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_INSTBTPOWER__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_INSTALLERCODEAPM__C", StringType(), True, {}),
            StructField("FALCON_FLD_INSTALLERCODE__C", StringType(), True, {}),
            StructField("FALCON_FLD_INSTALLERNIFAPM__C", StringType(), True, {}),
            StructField("FALCON_FLD_INSTALLERNIF__C", StringType(), True, {}),
            StructField("FALCON_FLD_MAXDISCOUNTUNITS__C", StringType(), True, {}),
            StructField("FALCON_FLD_MAXDISCOUNT__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_NUMYEARCONTRACT__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_PSVA__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_PROPOSEDCHANGEDATE__C", TimestampType(), True, {}),
            StructField(
                "FALCON_FLD_REGENERATE_FORECAST_TACITA__C",
                BooleanType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_REGENERATE_FORECAST_TARIFA__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_SETTLEMENTAXCX__C", StringType(), True, {}),
            StructField("FALCON_FLD_SUPPLYTENSIONAPM__C", StringType(), True, {}),
            StructField("FALCON_FLD_SUPPLYTENSIONCIE__C", StringType(), True, {}),
            StructField("FALCON_FLD_SUPPLYTYPE__C", StringType(), True, {}),
            StructField("FALCON_FLD_TOTALEFFICIENCYFEE__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_TYPEDISCOUNT__C", StringType(), True, {}),
            StructField("FALCON_FLD_TYPEOFCONTRACTATR__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_UNINTERRUPTIBLEPOWER__C",
                DoubleType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_UNITDISCOUNT__C", StringType(), True, {}),
            StructField("FALCON_FLD_VALIDITYCIE__C", StringType(), True, {}),
            StructField("FALCON_FLD_CASECT__C", StringType(), True, {}),
            StructField("FALCON_FLD_DISCOUNT__C", DoubleType(), True, {}),
            StructField("FALCON_FLD_NOTIFYDIST__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_TRADEFEE__C", StringType(), True, {}),
            StructField("FALCON_FLD_TYPECHANGEDATE__C", StringType(), True, {}),
            StructField(
                "FALCON_FLD_STATUSDATELASTCHANGE__C",
                TimestampType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_GREENPRODUCTMIGRADO__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_DISCOUNTAUX__C", DoubleType(), True, {}),
            StructField(
                "FALCON_FLD_COUNTERPLANTSATELLITE__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_CAMPANA_MIGRADA__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_ID_AGREGACION__C", StringType(), True, {}),
            StructField("FALCON_FLD_UNITDISCOUNTAUX__C", StringType(), True, {}),
            StructField("FALCON_FLD_CONTRACTDOCUMENT__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_UPDATECONTRACT__C", BooleanType(), True, {}),
            StructField(
                "FALCON_FLD_DESCRIPTIONERRORUPDATETD__C",
                StringType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_ERRORUPDATETD__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_UPDATEDTD__C", BooleanType(), True, {}),
            StructField(
                "FALCON_FLD_COMMISSIONPAYMENTTYPE__C",
                StringType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_ISQUOTEAUTORENEW__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_NOVISIBLEAGENCY__C", BooleanType(), True, {}),
            StructField("FALCON_FLD_FINANCIACIONEE__C", StringType(), True, {}),
            StructField("FALCON_FLD_KAM_AXPO__C", StringType(), True, {}),
            StructField("FALCON_FLD_NOPERMANENCIA__C", BooleanType(), True, {}),
            StructField(
                "FALCON_FLD_COMMISSIONBYINVOICE__C",
                BooleanType(),
                True,
                {},
            ),
            StructField("FALCON_FLD_LP__C", BooleanType(), True, {}),
            StructField(
                "FALCON_FLD_DOCUMENTATIONRECEIPTDATE__C",
                TimestampType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ANUALP1KWH__C",
                DoubleType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ANUALP2KWH__C",
                DoubleType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ANUALP3KWH__C",
                DoubleType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ANUALP4KWH__C",
                DoubleType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ANUALP5KWH__C",
                DoubleType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ANUALP6KWH__C",
                DoubleType(),
                True,
                {},
            ),
            StructField(
                "FALCON_FLD_ANNUALCONSSIGNED__C",
                DoubleType(),
                True,
                {},
            ),
            StructField(
                "SRC_CREATED_BY",
                StringType(),
                True,
                {},
            ),
            StructField(
                "SRC_CREATED_AT",
                TimestampType(),
                True,
                {},
            ),
        ]
    ),
    comment="Salesforce contract data for electricity and energy products (bronze layer).",
    sources=(TableIdentifier(catalog="neuron_aa_prod", schema="salesforce_rep", name="contract"),),
    primary_keys=("ID",),
    tags={
        "License": "Licence",
        "Confidentiality Level": "C2_Internal",
        "Personal sensitive information": "No PII",
        "Source System": "Neuron",
        "LPI": "Salesforce_AXPO-IBERIA_Neuron",
        "Data Owner": "Ignacio Ortiz de Zuniga",
    },
)
