from __future__ import annotations

from pyspark.sql.types import (
    ArrayType,
    BooleanType,
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

from data_platform.data_model import StaticTableModel, TableIdentifier
from data_platform.data_model.metadata_common import standard_columns, standard_tags

price_volume_transmission_capacity_auction_table = StaticTableModel(
    identifier=TableIdentifier(catalog="silver", schema="jao", name="price_volume_transmission_capacity_auction"),
    schema=StructType([
        StructField("auction_id", StringType(), True, {"comment": "Identifier of the auction"}),
        StructField("auction_close", TimestampType(), True, {"comment": "Closing timestamp of the auction"}),
        StructField("delivery_start", TimestampType(), True, {"comment": "Start timestamp of the capacity (aggregated from product_hour & auction date). DST shifts are already accounted for."}),
        StructField("delivery_end", TimestampType(), True, {"comment": "End timestamp of the capacity (aggregated from product_hour & auction date). DST shifts are already accounted for."}),
        StructField("duration", StringType(), True, {"comment": "Duration of the product in hours"}),
        StructField("corridor_code", StringType(), True, {"comment": "Combined raw code for between which countries and through which cable the capacity applies for"}),
        StructField("from_area", StringType(), True, {"comment": "The source area the capacity applies for"}),
        StructField("to_area", StringType(), True, {"comment": "The target area the capacity applies for"}),
        StructField("cable_info", StringType(), True, {"comment": "The cable of which the capacity applies for"}),
        StructField("schedule_type", StringType(), True, {"comment": "Schedule info (e.g. OnPeak, Everyday) taken from product_hour"}),
        StructField("ftroption", StringType(), True, {"comment": "Indicates whether FTR option applies (financial compensation on resale)"}),
        StructField("horizon_name", StringType(), True, {"comment": "Time horizon: Intraday, Daily, Weekly, Monthly"}),
        StructField("maintenances", ArrayType(StructType([StructField("corridor_code", StringType(), True), StructField("offered_capacity", DoubleType(), True), StructField("atc", DoubleType(), True), StructField("period_start", TimestampType(), True), StructField("period_stop", TimestampType(), True), StructField("delivery_minutes", DoubleType(), True), StructField("reduced_offered_capacity", DoubleType(), True)])), True, {"comment": "Potential maintenance periods on the connection"}),
        StructField("result_comment", StringType(), True, {"comment": "Comments on the auction result"}),
        StructField("offered_capacity", DoubleType(), True, {"comment": "Offered capacity on the auction"}),
        StructField("requested_capacity", DoubleType(), True, {"comment": "Requested capacity on the auction"}),
        StructField("allocated_capacity", DoubleType(), True, {"comment": "Allocated capacity on the auction"}),
        StructField("product_id", StringType(), True, {"comment": "Product identifier denoting the hour"}),
        StructField("auction_price", DoubleType(), True, {"comment": "Resulting price of the auction"}),
        StructField("result_additional_message", StringType(), True, {"comment": "Additional messages for participants"}),
        StructField("xn_rule", StringType(), True, {"comment": "Number of installments included in first invoice"}),
        StructField("winning_parties_eic_code", ArrayType(StringType()), True, {"comment": "EIC codes of winning parties"}),
        StructField("operational_message", StringType(), True, {"comment": "Formal communication about significant events"}),
        StructField("product_comment", StringType(), True, {"comment": "Additional information for specific products"}),
        StructField("bid_party_count", IntegerType(), True, {"comment": "Number of bidders on the auction"}),
        StructField("product_offered_capacity", DoubleType(), True, {"comment": "Offered capacity for the product"}),
        StructField("product_atc", DoubleType(), True, {"comment": "Available transmission capacity (ATC)"}),
        StructField("product_resold_capacity", DoubleType(), True, {"comment": "Previously allocated LTTRs returned for reallocation"}),
        StructField("product_winner_party_count", IntegerType(), True, {"comment": "Number of winning parties for the product"}),
        StructField("cancelled", BooleanType(), True, {"comment": "True if the auction was cancelled"}),
        standard_columns.UpdatedAtSourceColumn.to_struct_field(),
        standard_columns.CommodityColumn.to_struct_field(),
        standard_columns.LicenseColumn.to_struct_field(),
        standard_columns.DataSourceColumn.to_struct_field(),
        standard_columns.DataSystemColumn.to_struct_field(),
    ]),
    comment="Auction data from JAO on long-term transmission rights (LTTRs).\ndelivery_start / delivery_end are derived from product_hour and auction date.\nFor OnPeak / Everyday products hours are normalised to 00:00; DST shifts handled.",
    sources=[TableIdentifier(catalog="bronze", schema="jao", name="auction")],
    primary_keys=("delivery_start", "delivery_end", "corridor_code"),
    tags={
        standard_tags.ConfidentialityLevel.KEY: standard_tags.ConfidentialityLevel.C2_INTERNAL,
        standard_tags.DataDomain.KEY: standard_tags.DataDomain.MARKET,
        standard_tags.DataOwner.KEY: standard_tags.DataOwner.KNUT_STENSROD,
        standard_tags.DataSubdomain.KEY: standard_tags.DataSubdomain.TRANSMISSION,
        standard_tags.LicensedData.KEY: standard_tags.LicensedData.FALSE,
        standard_tags.PIIClassification.KEY: standard_tags.PIIClassification.NO_PII,
    },
)
