from pyspark.sql.types import DateType, DecimalType, StringType, StructField, StructType

from data_platform.data_model import StaticTableModel, TableIdentifier
from data_platform.data_model.metadata_common import standard_columns, standard_tags

asset_table = StaticTableModel(
    identifier=TableIdentifier(catalog="silver", schema="ckw", name="asset"),
    schema=StructType([
        standard_columns.LicenseColumn.to_struct_field(),
        StructField("plant_number", StringType(), True, {"comment": "Identifier for the plant"}),
        StructField("plant_creation_date", DateType(), True, {"comment": "Date when the plant was created"}),
        StructField("plant_deleted_flag", StringType(), True, {"comment": "Flag indicating if the plant is deleted"}),
        StructField("plant_voltage_level_id", StringType(), True, {"comment": "Identifier for the plants voltage level"}),
        StructField("tariff_type_id", StringType(), True, {"comment": "Identifier for the tariff type"}),
        StructField("consumption_point_deleted_flag", StringType(), True, {"comment": "Flag indicating if the consumption point is deleted"}),
        StructField("consumption_point_location_addition_1", StringType(), True, {"comment": "Additional location information for the consumption point"}),
        StructField("connection_object_street", StringType(), True, {"comment": "Street name of the connection object"}),
        StructField("connection_object_house_number_1", StringType(), True, {"comment": "Primary house number of the connection object"}),
        StructField("connection_object_house_number_2", StringType(), True, {"comment": "Secondary house number of the connection object"}),
        StructField("connection_object_house_number_3", StringType(), True, {"comment": "Tertiary house number of the connection object"}),
        StructField("connection_object_postal_code_1", StringType(), True, {"comment": "Primary postal code of the connection object"}),
        StructField("connection_object_city_town_1", StringType(), True, {"comment": "Primary city or town of the connection object"}),
        StructField("connection_object_city_town_2", StringType(), True, {"comment": "Secondary city or town of the connection object"}),
        StructField("connection_object_country_id", StringType(), True, {"comment": "Identifier for the country of the connection object"}),
        StructField("connection_object_region_id", StringType(), True, {"comment": "Identifier for the region of the connection object"}),
        StructField("connection_object_regional_structure_id", StringType(), True, {"comment": "Identifier for the regional structure of the connection object"}),
        StructField("connection_object_regional_structure_name", StringType(), True, {"comment": "Name of the regional structure of the connection object"}),
        StructField("device_authorized_power", DecimalType(10, 0), True, {"comment": "Authorized power of the device"}),
        StructField("device_authorized_power_for_feed_in", DecimalType(10, 1), True, {"comment": "Authorized feed-in power of the device"}),
        StructField("tpl_maximum_consumption_power", DecimalType(10, 0), True, {"comment": "Maximum consumption power of the device"}),
        StructField("tpl_maximum_feed_in_power", DecimalType(10, 1), True, {"comment": "Maximum feed-in power of the device"}),
        StructField("device_installation_date", DateType(), True, {"comment": "Date when the device was installed"}),
        StructField("device_sealing_date", DateType(), True, {"comment": "Date when the device was sealed"}),
        StructField("metering_point_type_id", StringType(), True, {"comment": "Identifier for the metering point type"}),
        StructField("load_profile_measured_flag", StringType(), True, {"comment": "Flag indicating if the load profile is measured"}),
        StructField("meter_active_power_flag", StringType(), True, {"comment": "Flag indicating if the meter measures active power"}),
        StructField("eea_apparent_power", DecimalType(7, 1), True, {"comment": "Apparent power of the EEA"}),
        StructField("eea_type_id", StringType(), True, {"comment": "Identifier for the EEA type"}),
        StructField("eea_type_name", StringType(), True, {"comment": "Name of the EEA type"}),
        StructField("eea_commissioning_date", DateType(), True, {"comment": "Date when the EEA was commissioned"}),
        StructField("eea_commissioning", StringType(), True, {"comment": "Commissioning status of the EEA"}),
        StructField("eea_kev_flag", StringType(), True, {"comment": "Flag indicating if the EEA is KEV"}),
        StructField("eea_kev_from_date", DateType(), True, {"comment": "Start date for the KEV status of the EEA"}),
        StructField("eea_kev_until_date", DateType(), True, {"comment": "End date for the KEV status of the EEA"}),
        StructField("year_of_construction", StringType(), True, {"comment": "Year when the construction was completed"}),
        StructField("metering_point_id", StringType(), True, {"comment": "Identifier for the metering point"}),
        standard_columns.DataSystemColumn.to_struct_field(),
        standard_columns.DataSourceColumn.to_struct_field(),
    ]),
    comment="Contains information about various assets, including details such as plant numbers, voltage levels, tariff types, and connection locations. It also includes data on device installation, metering points, and power specifications.",
    sources=[
        TableIdentifier(catalog="bronze", schema="ckw", name="tbl_d_anlage_filtered"),
        TableIdentifier(catalog="bronze", schema="ckw", name="attribute"),
    ],
    tags={
        standard_tags.ConfidentialityLevel.KEY: standard_tags.ConfidentialityLevel.C2_INTERNAL,
        standard_tags.DataDomain.KEY: standard_tags.DataDomain.COUNTERPARTY,
        standard_tags.LicensedData.KEY: standard_tags.LicensedData.TRUE,
        standard_tags.PIIClassification.KEY: standard_tags.PIIClassification.NO_PII,
        standard_tags.DataOwner.KEY: standard_tags.DataOwner.REMI_JANNER,
    },
    primary_keys=(),
    partition_cols=(),
    liquid_cluster_cols=(),
)
