# Databricks notebook source
from __future__ import annotations

from pyspark.sql.types import DoubleType, StringType, StructField, StructType

from data_platform.data_model import StaticTableModel, TableIdentifier
from data_platform.data_model.metadata_common import standard_columns, standard_tags
from data_platform.data_model.silver.meteologica.common_variables import METEOLOGICA_COMMON_TAGS

ecmwf_ens_forecast_table = StaticTableModel(
    identifier=TableIdentifier(catalog="silver", schema="meteologica", name="ecmwf_ens_forecast"),
    schema=StructType(
        [
            standard_columns.DeliveryStartColumn.to_struct_field(),
            standard_columns.DeliveryEndColumn.to_struct_field(),
            standard_columns.DurationColumn.to_struct_field(),
            StructField("content_id", StringType(), True, {"comment": "Unique identifier for the content"}),
            StructField("average", DoubleType(), True, {"comment": "Average value of the forecast"}),
            StructField("bottom", DoubleType(), True, {"comment": "Bottom value of the forecast range"}),
            StructField("top", DoubleType(), True, {"comment": "Top value of the forecast range"}),
            StructField("ens00", DoubleType(), True, {"comment": "Value of relative ensemble simulation 00"}),
            StructField("ens01", DoubleType(), True, {"comment": "Value of relative ensemble simulation 01"}),
            StructField("ens02", DoubleType(), True, {"comment": "Value of relative ensemble simulation 02"}),
            StructField("ens03", DoubleType(), True, {"comment": "Value of relative ensemble simulation 03"}),
            StructField("ens04", DoubleType(), True, {"comment": "Value of relative ensemble simulation 04"}),
            StructField("ens05", DoubleType(), True, {"comment": "Value of relative ensemble simulation 05"}),
            StructField("ens06", DoubleType(), True, {"comment": "Value of relative ensemble simulation 06"}),
            StructField("ens07", DoubleType(), True, {"comment": "Value of relative ensemble simulation 07"}),
            StructField("ens08", DoubleType(), True, {"comment": "Value of relative ensemble simulation 08"}),
            StructField("ens09", DoubleType(), True, {"comment": "Value of relative ensemble simulation 09"}),
            StructField("ens10", DoubleType(), True, {"comment": "Value of relative ensemble simulation 10"}),
            StructField("ens11", DoubleType(), True, {"comment": "Value of relative ensemble simulation 11"}),
            StructField("ens12", DoubleType(), True, {"comment": "Value of relative ensemble simulation 12"}),
            StructField("ens13", DoubleType(), True, {"comment": "Value of relative ensemble simulation 13"}),
            StructField("ens14", DoubleType(), True, {"comment": "Value of relative ensemble simulation 14"}),
            StructField("ens15", DoubleType(), True, {"comment": "Value of relative ensemble simulation 15"}),
            StructField("ens16", DoubleType(), True, {"comment": "Value of relative ensemble simulation 16"}),
            StructField("ens17", DoubleType(), True, {"comment": "Value of relative ensemble simulation 17"}),
            StructField("ens18", DoubleType(), True, {"comment": "Value of relative ensemble simulation 18"}),
            StructField("ens19", DoubleType(), True, {"comment": "Value of relative ensemble simulation 19"}),
            StructField("ens20", DoubleType(), True, {"comment": "Value of relative ensemble simulation 20"}),
            StructField("ens21", DoubleType(), True, {"comment": "Value of relative ensemble simulation 21"}),
            StructField("ens22", DoubleType(), True, {"comment": "Value of relative ensemble simulation 22"}),
            StructField("ens23", DoubleType(), True, {"comment": "Value of relative ensemble simulation 23"}),
            StructField("ens24", DoubleType(), True, {"comment": "Value of relative ensemble simulation 24"}),
            StructField("ens25", DoubleType(), True, {"comment": "Value of relative ensemble simulation 25"}),
            StructField("ens26", DoubleType(), True, {"comment": "Value of relative ensemble simulation 26"}),
            StructField("ens27", DoubleType(), True, {"comment": "Value of relative ensemble simulation 27"}),
            StructField("ens28", DoubleType(), True, {"comment": "Value of relative ensemble simulation 28"}),
            StructField("ens29", DoubleType(), True, {"comment": "Value of relative ensemble simulation 29"}),
            StructField("ens30", DoubleType(), True, {"comment": "Value of relative ensemble simulation 30"}),
            StructField("ens31", DoubleType(), True, {"comment": "Value of relative ensemble simulation 31"}),
            StructField("ens32", DoubleType(), True, {"comment": "Value of relative ensemble simulation 32"}),
            StructField("ens33", DoubleType(), True, {"comment": "Value of relative ensemble simulation 33"}),
            StructField("ens34", DoubleType(), True, {"comment": "Value of relative ensemble simulation 34"}),
            StructField("ens35", DoubleType(), True, {"comment": "Value of relative ensemble simulation 35"}),
            StructField("ens36", DoubleType(), True, {"comment": "Value of relative ensemble simulation 36"}),
            StructField("ens37", DoubleType(), True, {"comment": "Value of relative ensemble simulation 37"}),
            StructField("ens38", DoubleType(), True, {"comment": "Value of relative ensemble simulation 38"}),
            StructField("ens39", DoubleType(), True, {"comment": "Value of relative ensemble simulation 39"}),
            StructField("ens40", DoubleType(), True, {"comment": "Value of relative ensemble simulation 40"}),
            StructField("ens41", DoubleType(), True, {"comment": "Value of relative ensemble simulation 41"}),
            StructField("ens42", DoubleType(), True, {"comment": "Value of relative ensemble simulation 42"}),
            StructField("ens43", DoubleType(), True, {"comment": "Value of relative ensemble simulation 43"}),
            StructField("ens44", DoubleType(), True, {"comment": "Value of relative ensemble simulation 44"}),
            StructField("ens45", DoubleType(), True, {"comment": "Value of relative ensemble simulation 45"}),
            StructField("ens46", DoubleType(), True, {"comment": "Value of relative ensemble simulation 46"}),
            StructField("ens47", DoubleType(), True, {"comment": "Value of relative ensemble simulation 47"}),
            StructField("ens48", DoubleType(), True, {"comment": "Value of relative ensemble simulation 48"}),
            StructField("ens49", DoubleType(), True, {"comment": "Value of relative ensemble simulation 49"}),
            StructField("ens50", DoubleType(), True, {"comment": "Value of relative ensemble simulation 50"}),
            StructField("installed_capacity", StringType(), True, {"comment": "Installed capacity for the forecast"}),
            standard_columns.UnitColumn.to_struct_field(nullable=True),
            StructField("content_name", StringType(), True, {"comment": "Name of the content"}),
            StructField("issue_date", StringType(), True, {"comment": "Date when the forecast was issued"}),
            StructField("update_id", StringType(), True, {"comment": "Identifier for the update"}),
            standard_columns.LicenseColumn.to_struct_field(),
            standard_columns.DataSourceColumn.to_struct_field(),
            standard_columns.DataSystemColumn.to_struct_field(),
        ]
    ),
    comment="The table contains forecasts of power generation and demand across various countries from European Centre for Medium-Range Weather Forecasts (ECMWF) ensemble model.",
    sources=[TableIdentifier(catalog="bronze", schema="meteologica", name="ecmwf_ens_forecast")],
    primary_keys=("update_id", "issue_date", "content_id", "delivery_start"),
    partition_cols=("update_id",),
    tags={
        **METEOLOGICA_COMMON_TAGS,
        standard_tags.DataSubdomain.KEY: "; ".join([standard_tags.DataSubdomain.PRODUCTION, standard_tags.DataSubdomain.DEMAND_AND_SUPPLY]),
    },
)
