"""Salesforce asset data for electricity and energy products (silver layer)."""

from __future__ import annotations

from pyspark.sql.types import BooleanType, DateType, DecimalType, StringType, StructField, StructType, TimestampType

from data_platform.data_model import StaticTableModel, TableIdentifier
from data_platform.data_model.metadata_common.tags_enum import DataDomain
from data_platform.data_model.silver.neuron import neuron_common
from data_platform.data_model.metadata_common.common_columns import standard_columns

salesforce_rep_asset_table = StaticTableModel(
    identifier=TableIdentifier(catalog="silver", schema="neuron", name="salesforce_rep_asset"),
    schema=StructType([
        StructField("id", StringType(), True, {"comment": "Unique asset identifier (Salesforce primary key)."}),
        StructField("contact_id", StringType(), True, {"comment": "Contact identifier associated with the asset."}),
        StructField("account_id", StringType(), True, {"comment": "Account identifier associated with the asset."}),
        StructField("parent_id", StringType(), True, {"comment": "Parent asset identifier (if this asset is part of a hierarchy)."}),
        StructField("root_asset_id", StringType(), True, {"comment": "Root asset identifier for the asset hierarchy."}),
        StructField("product_2_id", StringType(), True, {"comment": "Salesforce Product2 object identifier."}),
        StructField("product_code", StringType(), True, {"comment": "Product code associated with the asset."}),
        StructField("product_family", StringType(), True, {"comment": "Product family classification."}),
        StructField("product_description", StringType(), True, {"comment": "Description of the product."}),
        StructField("is_competitor_product", BooleanType(), True, {"comment": "Flag indicating if the asset is a competitor's product."}),
        StructField("created_date", TimestampType(), True, {"comment": "Timestamp when the asset record was created, Madrid/Europe."}),
        StructField("created_by_id", StringType(), True, {"comment": "User who created the asset record."}),
        StructField("last_modified_date", TimestampType(), True, {"comment": "Timestamp when the asset record was last modified, Madrid/Europe."}),
        StructField("last_modified_by_id", StringType(), True, {"comment": "User who last modified the asset record."}),
        StructField("system_mod_stamp", TimestampType(), True, {"comment": "System modification timestamp, Madrid/Europe."}),
        StructField("is_deleted", BooleanType(), True, {"comment": "Indicates if the asset has been deleted (Salesforce soft delete)."}),
        StructField("name", StringType(), True, {"comment": "Asset name."}),
        StructField("serial_number", StringType(), True, {"comment": "Serial number of the asset."}),
        StructField("install_date", DateType(), True, {"comment": "Date when the asset was installed."}),
        StructField("manufacture_date", DateType(), True, {"comment": "Date when the asset was manufactured."}),
        StructField("status_reason", StringType(), True, {"comment": "Reason for the current status of the asset."}),
        StructField("uuid", StringType(), True, {"comment": "Universally unique identifier for the asset."}),
        StructField("external_identifier", StringType(), True, {"comment": "External system identifier for the asset."}),
        StructField("purchase_date", DateType(), True, {"comment": "Date when the asset was purchased."}),
        StructField("usage_end_date", DateType(), True, {"comment": "Date when the asset usage ends or ended."}),
        StructField("status", StringType(), True, {"comment": "Current status of the asset."}),
        StructField("digital_asset_status", StringType(), True, {"comment": "Digital asset status (if applicable)."}),
        StructField("price", DecimalType(18, 2), True, {"comment": "Asset price or value (EUR)."}),
        StructField("quantity", DecimalType(12, 2), True, {"comment": "Quantity of the asset."}),
        StructField("description", StringType(), True, {"comment": "General description of the asset."}),
        StructField("owner_id", StringType(), True, {"comment": "Owner (user or team) of the asset record."}),
        StructField("record_type_id", StringType(), True, {"comment": "Salesforce record type identifier."}),
        StructField("asset_provided_by_id", StringType(), True, {"comment": "Provider or supplier of the asset."}),
        StructField("asset_serviced_by_id", StringType(), True, {"comment": "Service provider responsible for the asset."}),
        StructField("is_internal", BooleanType(), True, {"comment": "Flag indicating if the asset is internal (not customer-facing)."}),
        StructField("asset_level", DecimalType(38, 0), True, {"comment": "Hierarchy level of the asset (if applicable)."}),
        StructField("stock_keeping_unit", StringType(), True, {"comment": "SKU (stock keeping unit) for the asset."}),
        StructField("consequence_of_failure", StringType(), True, {"comment": "Business or operational impact if the asset fails."}),
        StructField("external_id_contracted_product", StringType(), True, {"comment": "External ID for the contracted product (custom field)."}),
        StructField("falcon_fld_annual_cons", DecimalType(18, 2), True, {"comment": "Annual energy consumption (custom field)."}),
        StructField("falcon_fld_cups", StringType(), True, {"comment": "CUPS code for the supply point (custom field)."}),
        StructField("falcon_fld_commercial_agreement", StringType(), True, {"comment": "Commercial agreement reference (custom field)."}),
        StructField("falcon_fld_commissioner", BooleanType(), True, {"comment": "Commissioner flag (custom field)."}),
        StructField("falcon_fld_contract", StringType(), True, {"comment": "Contract reference (custom field)."}),
        StructField("falcon_fld_contracted_product_code_aux", StringType(), True, {"comment": "Auxiliary contracted product code (custom field)."}),
        StructField("falcon_fld_contracted_product", BooleanType(), True, {"comment": "Flag indicating if the asset is a contracted product (custom field)."}),
        StructField("falcon_fld_contracted_qa", DecimalType(18, 0), True, {"comment": "Contracted QA value (custom field)."}),
        StructField("falcon_fld_contracted_qd", DecimalType(18, 0), True, {"comment": "Contracted QD value (custom field)."}),
        StructField("falcon_fld_contracted_qh", DecimalType(18, 0), True, {"comment": "Contracted QH value (custom field)."}),
        StructField("falcon_fld_end_date_version", DateType(), True, {"comment": "End date for the asset version (custom field)."}),
        StructField("falcon_fld_id_base_price", StringType(), True, {"comment": "Base price identifier (custom field)."}),
        StructField("falcon_fld_master_product", StringType(), True, {"comment": "Master product reference (custom field)."}),
        StructField("falcon_fld_oil_special_tax_type", StringType(), True, {"comment": "Oil special tax type (custom field)."}),
        StructField("falcon_fld_partner_margin", DecimalType(18, 2), True, {"comment": "Partner margin amount (custom field)."}),
        StructField("falcon_fld_prices_level", StringType(), True, {"comment": "Prices level or tier (custom field)."}),
        StructField("falcon_fld_quote_cups_aux", StringType(), True, {"comment": "Quote CUPS auxiliary identifier (custom field)."}),
        StructField("falcon_fld_start_date_version", DateType(), True, {"comment": "Start date for the asset version (custom field)."}),
        StructField("falcon_fld_synchronized", BooleanType(), True, {"comment": "Flag indicating if the asset is synchronized (custom field)."}),
        StructField("falcon_fld_toll", StringType(), True, {"comment": "Toll identifier (custom field)."}),
        StructField("falcon_fld_asset_version", DecimalType(10, 0), True, {"comment": "Asset version number (custom field)."}),
        StructField("falcon_fld_last_pc", BooleanType(), True, {"comment": "Flag for last PC (custom field)."}),
        StructField("falcon_fld_amortization_period", DecimalType(18, 0), True, {"comment": "Amortization period for the asset (custom field)."}),
        StructField("falcon_fld_amount_efficiency", DecimalType(18, 2), True, {"comment": "Efficiency amount (custom field)."}),
        StructField("falcon_fld_crm_commission", DecimalType(18, 2), True, {"comment": "CRM commission amount (custom field)."}),
        StructField("falcon_fld_collection_unit", StringType(), True, {"comment": "Collection unit reference (custom field)."}),
        StructField("falcon_fld_conformity_declaration_date", DateType(), True, {"comment": "Conformity declaration date (custom field)."}),
        StructField("falcon_fld_contract_power_p1", DecimalType(16, 4), True, {"comment": "Contracted power for period P1 (kW, custom field)."}),
        StructField("falcon_fld_contract_power_p2", DecimalType(16, 4), True, {"comment": "Contracted power for period P2 (kW, custom field)."}),
        StructField("falcon_fld_contract_power_p3", DecimalType(16, 4), True, {"comment": "Contracted power for period P3 (kW, custom field)."}),
        StructField("falcon_fld_contract_power_p4", DecimalType(16, 4), True, {"comment": "Contracted power for period P4 (kW, custom field)."}),
        StructField("falcon_fld_contract_power_p5", DecimalType(16, 4), True, {"comment": "Contracted power for period P5 (kW, custom field)."}),
        StructField("falcon_fld_contract_power_p6", DecimalType(16, 4), True, {"comment": "Contracted power for period P6 (kW, custom field)."}),
        StructField("falcon_fld_duration", DecimalType(3, 0), True, {"comment": "Asset duration (custom field)."}),
        StructField("falcon_fld_extractions_completed", DecimalType(18, 0), True, {"comment": "Number of completed extractions (custom field)."}),
        StructField("falcon_fld_financing_period", StringType(), True, {"comment": "Financing period (custom field)."}),
        StructField("falcon_fld_inflation", DecimalType(3, 0), True, {"comment": "Inflation rate or code (custom field)."}),
        StructField("falcon_fld_installed_total_power_fv", DecimalType(18, 1), True, {"comment": "Total installed photovoltaic power (kW, custom field)."}),
        StructField("falcon_fld_milestones_count", DecimalType(18, 0), True, {"comment": "Milestones count (custom field)."}),
        StructField("falcon_fld_num_total_milestones", DecimalType(18, 0), True, {"comment": "Total number of milestones (custom field)."}),
        StructField("falcon_fld_operation_maintenance_costs", DecimalType(18, 2), True, {"comment": "Operation and maintenance costs (custom field)."}),
        StructField("falcon_fld_payment_time", StringType(), True, {"comment": "Payment time or schedule (custom field)."}),
        StructField("falcon_fld_price", DecimalType(12, 2), True, {"comment": "Asset price (custom field)."}),
        StructField("falcon_fld_product_name", StringType(), True, {"comment": "Product name (custom field)."}),
        StructField("falcon_fld_quality_control_efficiency", BooleanType(), True, {"comment": "Quality control efficiency flag (custom field)."}),
        StructField("falcon_fld_amount_efficiency_fv", DecimalType(18, 2), True, {"comment": "Photovoltaic efficiency amount (custom field)."}),
        neuron_common.SrcCreatedByColumn.to_struct_field(),
        neuron_common.SrcCreatedAtColumn.to_struct_field(),
        standard_columns.LicenseColumn.to_struct_field(),
    ]),
    comment="Salesforce asset data for electricity and energy products (silver layer).",
    sources=(TableIdentifier(catalog="bronze", schema="neuron", name="salesforce_rep_asset"),),
    primary_keys=("id",),
    tags={
        **neuron_common.NEURON_COMMON_TAGS,
        DataDomain.KEY: DataDomain.COUNTERPARTY,
    },
)
