"""Salesforce contract data for electricity and energy products (silver layer)."""

from __future__ import annotations

from pyspark.sql.types import BooleanType, DecimalType, DoubleType, StringType, StructField, StructType, TimestampType

from data_platform.data_model import StaticTableModel, TableIdentifier
from data_platform.data_model.metadata_common.tags_enum import DataDomain
from data_platform.data_model.silver.neuron import neuron_common
from data_platform.data_model.metadata_common.common_columns import standard_columns

salesforce_rep_contract_table = StaticTableModel(
    identifier=TableIdentifier(
        catalog="silver",
        schema="neuron",
        name="salesforce_rep_contract",
    ),
    schema=StructType([
        StructField("id", StringType(), True, {"comment": "Unique identifier for the contract (Salesforce primary key)."}),
        StructField("account_id", StringType(), True, {"comment": "Account identifier linked to the contract."}),
        StructField("pricebook_2_id", StringType(), True, {"comment": "Pricebook for contract pricing details."}),
        StructField("owner_expiration_notice", StringType(), True, {"comment": "Expiration notice for contract owner."}),
            StructField("start_date", TimestampType(), True, {"comment": "Contract start date."}),
            StructField("end_date", TimestampType(), True, {"comment": "Contract end date."}),
            StructField("billing_street", StringType(), True, {"comment": "Billing address street."}),
            StructField("billing_city", StringType(), True, {"comment": "Billing address city."}),
            StructField("billing_state", StringType(), True, {"comment": "Billing address state."}),
            StructField("billing_postal_code", StringType(), True, {"comment": "Billing address postal code."}),
            StructField("billing_country", StringType(), True, {"comment": "Billing address country."}),
            StructField("billing_state_code", StringType(), True, {"comment": "Billing address state code."}),
        StructField("billing_country_code", StringType(), True, {"comment": "Billing address country code."}),
        StructField("billing_latitude", DoubleType(), True, {"comment": "Billing address latitude (geo-coordinate)."}),
        StructField("billing_longitude", DoubleType(), True, {"comment": "Billing address longitude (geo-coordinate)."}),
        StructField("billing_geocode_accuracy", StringType(), True, {"comment": "Geocode accuracy for billing address."}),
            StructField("billing_address", StringType(), True, {"comment": "Full billing address."}),
            StructField("shipping_street", StringType(), True, {"comment": "Shipping address street."}),
            StructField("shipping_city", StringType(), True, {"comment": "Shipping address city."}),
            StructField("shipping_state", StringType(), True, {"comment": "Shipping address state."}),
            StructField("shipping_postal_code", StringType(), True, {"comment": "Shipping address postal code."}),
            StructField("shipping_country", StringType(), True, {"comment": "Shipping address country."}),
            StructField("shipping_state_code", StringType(), True, {"comment": "Shipping address state code."}),
        StructField("shipping_country_code", StringType(), True, {"comment": "Shipping address country code."}),
        StructField("shipping_latitude", DoubleType(), True, {"comment": "Shipping address latitude (geo-coordinate)."}),
        StructField("shipping_longitude", DoubleType(), True, {"comment": "Shipping address longitude (geo-coordinate)."}),
        StructField("shipping_geocode_accuracy", StringType(), True, {"comment": "Geocode accuracy for shipping address."}),
            StructField("shipping_address", StringType(), True, {"comment": "Full shipping address."}),
            StructField("contract_term", DecimalType(38, 0), True, {"comment": "Contract duration in months."}),
            StructField("owner_id", StringType(), True, {"comment": "User or team that owns the contract."}),
            StructField("status", StringType(), True, {"comment": "Current contract status."}),
            StructField("company_signed_id", StringType(), True, {"comment": "Identifier of company signatory."}),
            StructField("company_signed_date", TimestampType(), True, {"comment": "Date of company signature."}),
            StructField("customer_signed_id", StringType(), True, {"comment": "Identifier of customer signatory."}),
            StructField("customer_signed_title", StringType(), True, {"comment": "Title of customer signatory."}),
        StructField("customer_signed_date", TimestampType(), True, {"comment": "Date of customer signature."}),
        StructField("special_terms", StringType(), True, {"comment": "Special terms and conditions for the contract."}),
        StructField("activated_by_id", StringType(), True, {"comment": "User who activated the contract."}),
            StructField("activated_date", TimestampType(), True, {"comment": "Date contract was activated."}),
            StructField("status_code", StringType(), True, {"comment": "Internal status code for the contract."}),
            StructField("description", StringType(), True, {"comment": "Free-text description of the contract."}),
            StructField("record_type_id", StringType(), True, {"comment": "Salesforce record type identifier."}),
            StructField("name", StringType(), True, {"comment": "Contract name."}),
            StructField("is_deleted", BooleanType(), True, {"comment": "Flag for soft deletion (Salesforce logic)."}),
            StructField("contract_number", StringType(), True, {"comment": "Contract reference number."}),
        StructField("last_approved_date", TimestampType(), True, {"comment": "Date of last contract approval."}),
        StructField("created_date", TimestampType(), True, {"comment": "Timestamp when the contract was created, Madrid/Europe."}),
        StructField("created_by_id", StringType(), True, {"comment": "User who created the contract record."}),
        StructField("last_modified_date", TimestampType(), True, {"comment": "Timestamp of last modification, Madrid/Europe."}),
        StructField("last_modified_by_id", StringType(), True, {"comment": "User who last modified the contract."}),
        StructField("system_mod_stamp", TimestampType(), True, {"comment": "System modification timestamp, Madrid/Europe."}),
        StructField("last_activity_date", TimestampType(), True, {"comment": "Date of last activity on the contract."}),
        StructField("last_viewed_date", TimestampType(), True, {"comment": "Date contract was last viewed."}),
        StructField("last_referenced_date", TimestampType(), True, {"comment": "Date contract was last referenced."}),
            StructField("card_number", StringType(), True, {"comment": "Card number linked to the contract."}),
        StructField("card_type", StringType(), True, {"comment": "Card type for payment or identification."}),
        StructField("data_quality_description", StringType(), True, {"comment": "Description of data quality for this contract."}),
        StructField("data_quality_score", DoubleType(), True, {"comment": "Numerical data quality score."}),
            StructField("falcon_contact", StringType(), True, {"comment": "Falcon contact identifier."}),
        StructField("falcon_fld_atr_code", StringType(), True, {"comment": "Falcon ATR code (network access code)."}),
        StructField("falcon_fld_atr", BooleanType(), True, {"comment": "Falcon ATR flag (access to grid)."}),
            StructField("falcon_fld_advance_type", StringType(), True, {"comment": "Falcon contract advance type."}),
            StructField("falcon_fld_advance", BooleanType(), True, {"comment": "Falcon advance payment flag."}),
        StructField("falcon_fld_agency_client", StringType(), True, {"comment": "Falcon agency client identifier."}),
        StructField("falcon_fld_amount_advance", DoubleType(), True, {"comment": "Falcon advance amount (EUR)."}),
        StructField("falcon_fld_amount_fixed_fee", StringType(), True, {"comment": "Falcon fixed fee amount (EUR)."}),
        StructField("falcon_fld_annual_volume", DoubleType(), True, {"comment": "Falcon annual contracted energy volume (kWh)."}),
            StructField("falcon_fld_attention", StringType(), True, {"comment": "Falcon attention/notes field."}),
            StructField("falcon_fld_axpo_margin", DoubleType(), True, {"comment": "Falcon Axpo margin (EUR)."}),
            StructField("falcon_fld_bank_account", StringType(), True, {"comment": "Falcon bank account IBAN."}),
        StructField("falcon_fld_bill_shipping_method", StringType(), True, {"comment": "Falcon bill shipping method."}),
        StructField("falcon_fld_billing_address", StringType(), True, {"comment": "Falcon billing address."}),
        StructField("falcon_fld_bundle_billing", BooleanType(), True, {"comment": "Flag for bundle billing (Falcon logic)."}),
            StructField("falcon_fld_business_division", StringType(), True, {"comment": "Falcon business division."}),
            StructField("falcon_fld_business_line", StringType(), True, {"comment": "Falcon business line."}),
            StructField("falcon_fld_cif_nif", StringType(), True, {"comment": "Falcon CIF/NIF (tax ID)."}),
            StructField("falcon_fld_cups_address", StringType(), True, {"comment": "Falcon CUPS address."}),
            StructField("falcon_fld_cups_aux", StringType(), True, {"comment": "Falcon CUPS auxiliary identifier."}),
        StructField("falcon_fld_cups", StringType(), True, {"comment": "Falcon CUPS (supply point code)."}),
        StructField("falcon_fld_commercial_agreement", StringType(), True, {"comment": "Falcon commercial agreement reference."}),
        StructField("falcon_fld_contract_code_2", StringType(), True, {"comment": "Falcon secondary contract code."}),
            StructField("falcon_fld_contract_entity", BooleanType(), True, {"comment": "Falcon contract entity flag."}),
            StructField("falcon_fld_contract_type", StringType(), True, {"comment": "Falcon contract type."}),
            StructField("falcon_fld_contract_version", StringType(), True, {"comment": "Falcon contract version."}),
        StructField("falcon_fld_created_date", TimestampType(), True, {"comment": "Falcon contract creation date."}),
        StructField("falcon_fld_customer_order_num", StringType(), True, {"comment": "Falcon customer order number."}),
        StructField("falcon_fld_date_contract_recover", TimestampType(), True, {"comment": "Falcon contract recovery date."}),
            StructField("falcon_fld_document_url", StringType(), True, {"comment": "Falcon document URL."}),
            StructField("falcon_fld_download", StringType(), True, {"comment": "Falcon download link or reference."}),
        StructField("falcon_fld_early_cancel_penalty", BooleanType(), True, {"comment": "Falcon early cancellation penalty flag."}),
        StructField("falcon_fld_end_contract", DoubleType(), True, {"comment": "Falcon contract end indicator."}),
        StructField("falcon_fld_end_date_custom", TimestampType(), True, {"comment": "Falcon custom contract end date."}),
        StructField("falcon_fld_estimated_end_date_contract", TimestampType(), True, {"comment": "Falcon estimated contract end date."}),
        StructField("falcon_fld_estimated_start_date_contract", TimestampType(), True, {"comment": "Falcon estimated contract start date."}),
            StructField("falcon_fld_fixed_fee", BooleanType(), True, {"comment": "Falcon fixed fee flag."}),
        StructField("falcon_fld_formalized", DoubleType(), True, {"comment": "Falcon formalized contract indicator."}),
            StructField("falcon_fld_manager", StringType(), True, {"comment": "Falcon manager."}),
            StructField("falcon_fld_iban_value_for", StringType(), True, {"comment": "Falcon IBAN value for payment."}),
            StructField("falcon_fld_iban_for", StringType(), True, {"comment": "Falcon IBAN for payment."}),
            StructField("falcon_fld_ieh_industrial_use", StringType(), True, {"comment": "Falcon IEH industrial use."}),
            StructField("falcon_fld_ieh_use_generation", StringType(), True, {"comment": "Falcon IEH use generation."}),
            StructField("falcon_fld_ieh", StringType(), True, {"comment": "Falcon IEH code/reference."}),
        StructField("falcon_fld_id_base_price", StringType(), True, {"comment": "Falcon base price ID."}),
        StructField("falcon_fld_id_contract_old_crm", StringType(), True, {"comment": "Falcon old CRM contract ID."}),
            StructField("falcon_fld_imported", BooleanType(), True, {"comment": "Falcon imported contract flag."}),
            StructField("falcon_fld_kam_agent", StringType(), True, {"comment": "Falcon KAM agent identifier."}),
            StructField("falcon_fld_kam", StringType(), True, {"comment": "Falcon KAM (key account manager)."}),
            StructField("falcon_fld_marketer", StringType(), True, {"comment": "Falcon marketer identifier."}),
            StructField("falcon_fld_old_contract", StringType(), True, {"comment": "Falcon old contract reference."}),
        StructField("falcon_fld_termination_reason", StringType(), True, {"comment": "Falcon contract termination reason."}),
        StructField("falcon_fld_new_contract", DoubleType(), True, {"comment": "Falcon new contract indicator."}),
        StructField("falcon_fld_next_renewal_date", TimestampType(), True, {"comment": "Falcon next renewal date."}),
            StructField("falcon_fld_no_commission", BooleanType(), True, {"comment": "Falcon no commission flag."}),
            StructField("falcon_fld_payment_method_for", StringType(), True, {"comment": "Falcon payment method."}),
            StructField("falcon_fld_payment_method", StringType(), True, {"comment": "Falcon payment method."}),
            StructField("falcon_fld_payment_times_for", StringType(), True, {"comment": "Falcon payment times."}),
            StructField("falcon_fld_payment_times", StringType(), True, {"comment": "Falcon payment times."}),
            StructField("falcon_fld_penalty", DoubleType(), True, {"comment": "Falcon penalty amount."}),
        StructField("falcon_fld_physical_doc_received", BooleanType(), True, {"comment": "Falcon physical document received flag."}),
            StructField("falcon_fld_power", DoubleType(), True, {"comment": "Falcon contracted power (kW)."}),
            StructField("falcon_fld_previous_atr_code", StringType(), True, {"comment": "Falcon previous ATR code."}),
            StructField("falcon_fld_quote_new", StringType(), True, {"comment": "Falcon new quote reference."}),
            StructField("falcon_fld_rate", StringType(), True, {"comment": "Falcon contract rate/tariff."}),
            StructField("falcon_fld_ready_to_renew", BooleanType(), True, {"comment": "Falcon ready to renew flag."}),
            StructField("falcon_fld_reassigned", BooleanType(), True, {"comment": "Falcon reassigned flag."}),
        StructField("falcon_fld_renewal_complaint", BooleanType(), True, {"comment": "Falcon renewal complaint flag."}),
            StructField("falcon_fld_renewed", BooleanType(), True, {"comment": "Falcon renewed contract flag."}),
            StructField("falcon_fld_sepa", StringType(), True, {"comment": "Falcon SEPA code/reference."}),
            StructField("falcon_fld_swift_value", StringType(), True, {"comment": "Falcon SWIFT value for payments."}),
        StructField("falcon_fld_same_billing_conditions", BooleanType(), True, {"comment": "Falcon same billing conditions flag."}),
        StructField("falcon_fld_start_date_before_today", DoubleType(), True, {"comment": "Falcon start date before today indicator."}),
        StructField("falcon_fld_start_date_before_today_and_30", BooleanType(), True, {"comment": "Falcon start date before today and 30 days flag."}),
        StructField("falcon_fld_start_date_penalty", TimestampType(), True, {"comment": "Falcon start date penalty."}),
            StructField("falcon_fld_state", StringType(), True, {"comment": "Falcon contract state/region."}),
            StructField("falcon_fld_reference_code", StringType(), True, {"comment": "Falcon reference code."}),
            StructField("falcon_fld_synchronized", BooleanType(), True, {"comment": "Falcon synchronized flag."}),
        StructField("falcon_fld_synchronization_error", BooleanType(), True, {"comment": "Falcon synchronization error flag."}),
        StructField("falcon_fld_renewal_request_answered", BooleanType(), True, {"comment": "Falcon renewal request answered flag."}),
            StructField("falcon_fld_telmed", DoubleType(), True, {"comment": "Falcon telmed value."}),
            StructField("falcon_obj_template", StringType(), True, {"comment": "Falcon template object reference."}),
            StructField("falcon_fld_full_address", StringType(), True, {"comment": "Falcon full address."}),
            StructField("method_of_payment", StringType(), True, {"comment": "Payment method for the contract."}),
            StructField("paperless_billing", BooleanType(), True, {"comment": "Paperless billing flag."}),
            StructField("payment_day", StringType(), True, {"comment": "Payment day for the contract."}),
            StructField("falcon_fld_account_name", StringType(), True, {"comment": "Falcon account name."}),
            StructField("falcon_fld_contract_code", StringType(), True, {"comment": "Falcon contract code."}),
        StructField("falcon_fld_contract_code_formula", StringType(), True, {"comment": "Falcon contract code formula."}),
            StructField("falcon_fld_amount_advance_nav", DoubleType(), True, {"comment": "Falcon advance amount NAV."}),
            StructField("falcon_fld_first_rep", BooleanType(), True, {"comment": "Falcon first representative flag."}),
            StructField("falcon_fld_ieh_exempt", StringType(), True, {"comment": "Falcon IEH exempt code."}),
            StructField("falcon_fld_nav_ok", BooleanType(), True, {"comment": "Falcon NAV OK flag."}),
            StructField("falcon_fld_wso2_ok", BooleanType(), True, {"comment": "Falcon WSO2 OK flag."}),
            StructField("falcon_fld_all_sc", DoubleType(), True, {"comment": "Falcon all SC value."}),
            StructField("falcon_fld_all_sc_nav_ok", DoubleType(), True, {"comment": "Falcon all SC NAV OK value."}),
            StructField("falcon_fld_all_sc_wso2_ok", DoubleType(), True, {"comment": "Falcon all SC WSO2 OK value."}),
        StructField("falcon_fld_exempt_percentage", StringType(), True, {"comment": "Falcon exemption percentage."}),
            StructField("falcon_fld_prices_level", StringType(), True, {"comment": "Falcon prices level."}),
            StructField("falcon_fld_ieh_end_date_cie", TimestampType(), True, {"comment": "Falcon IEH end date CIE."}),
        StructField("falcon_fld_ieh_start_date_cie", TimestampType(), True, {"comment": "Falcon IEH start date CIE."}),
        StructField("falcon_fld_master_partner", StringType(), True, {"comment": "Falcon master partner identifier."}),
            StructField("falcon_fld_team_manager", StringType(), True, {"comment": "Falcon team manager identifier."}),
            StructField("falcon_fld_sub_partner", StringType(), True, {"comment": "Falcon sub partner identifier."}),
        StructField("falcon_fld_team_leader_commission", StringType(), True, {"comment": "Falcon team leader commission."}),
        StructField("falcon_fld_sub_agent_commission", StringType(), True, {"comment": "Falcon sub agent commission."}),
            StructField("falcon_fld_s3_ok", BooleanType(), True, {"comment": "Falcon S3 OK flag."}),
            StructField("falcon_fld_all_sc_s3_ok", DoubleType(), True, {"comment": "Falcon all SC S3 OK value."}),
        StructField("falcon_fld_master_agent_commission", StringType(), True, {"comment": "Falcon master agent commission."}),
        StructField("falcon_fld_early_resolution_date", TimestampType(), True, {"comment": "Falcon early resolution date."}),
            StructField("falcon_fld_advance_type_2", StringType(), True, {"comment": "Falcon advance type 2."}),
            StructField("falcon_fld_not_renew", BooleanType(), True, {"comment": "Falcon not renew flag."}),
        StructField("falcon_fld_amount_fixed_fee_qc", DoubleType(), True, {"comment": "Falcon fixed fee amount QC."}),
            StructField("falcon_fld_check_callidus", BooleanType(), True, {"comment": "Falcon check Callidus flag."}),
        StructField("falcon_fld_contract_code_final", StringType(), True, {"comment": "Falcon final contract code."}),
        StructField("falcon_fld_responsible_complaint", StringType(), True, {"comment": "Falcon responsible complaint."}),
        StructField("falcon_fld_reviewed_contract", BooleanType(), True, {"comment": "Falcon reviewed contract flag."}),
            StructField("falcon_fld_apm_code", StringType(), True, {"comment": "Falcon APM code."}),
            StructField("falcon_fld_active_period", DoubleType(), True, {"comment": "Falcon active period value."}),
        StructField("falcon_fld_benefit_cie_percent", StringType(), True, {"comment": "Falcon benefit CIE percentage."}),
            StructField("falcon_fld_brand_model", StringType(), True, {"comment": "Falcon brand model."}),
            StructField("falcon_fld_cie", StringType(), True, {"comment": "Falcon CIE."}),
            StructField("falcon_fld_cie_code", StringType(), True, {"comment": "Falcon CIE code."}),
            StructField("falcon_fld_crm_commission", DoubleType(), True, {"comment": "Falcon CRM commission amount."}),
            StructField("falcon_fld_comments", StringType(), True, {"comment": "Falcon comments field."}),
            StructField("falcon_fld_device_brand", StringType(), True, {"comment": "Falcon device brand."}),
            StructField("falcon_fld_device_model", StringType(), True, {"comment": "Falcon device model."}),
            StructField("falcon_fld_device_type", StringType(), True, {"comment": "Falcon device type."}),
        StructField("falcon_fld_effective_date_cie", TimestampType(), True, {"comment": "Falcon effective date CIE."}),
            StructField("falcon_fld_electronic_stamp", StringType(), True, {"comment": "Falcon electronic stamp."}),
        StructField("falcon_fld_emission_date_apm", TimestampType(), True, {"comment": "Falcon emission date APM."}),
        StructField("falcon_fld_exemption_ie_percent", DoubleType(), True, {"comment": "Falcon exemption IE percentage."}),
            StructField("falcon_fld_exemption_ie_type", StringType(), True, {"comment": "Falcon exemption IE type."}),
            StructField("falcon_fld_exemption_ie", BooleanType(), True, {"comment": "Falcon exemption IE flag."}),
        StructField("falcon_fld_expiration_date_apm", TimestampType(), True, {"comment": "Falcon expiration date APM."}),
        StructField("falcon_fld_extractions_completed", DoubleType(), True, {"comment": "Falcon extractions completed."}),
            StructField("falcon_fld_pricing_date", TimestampType(), True, {"comment": "Falcon pricing date."}),
            StructField("falcon_fld_green_product", BooleanType(), True, {"comment": "Falcon green product flag."}),
            StructField("falcon_fld_has_discount", BooleanType(), True, {"comment": "Falcon has discount flag."}),
            StructField("falcon_fld_instant_power", DoubleType(), True, {"comment": "Falcon instant power."}),
            StructField("falcon_fld_instant_bt_power", DoubleType(), True, {"comment": "Falcon instant BT power."}),
            StructField("falcon_fld_installer_code_apm", StringType(), True, {"comment": "Falcon installer code APM."}),
            StructField("falcon_fld_installer_code", StringType(), True, {"comment": "Falcon installer code."}),
            StructField("falcon_fld_installer_nif_apm", StringType(), True, {"comment": "Falcon installer NIF APM."}),
            StructField("falcon_fld_installer_nif", StringType(), True, {"comment": "Falcon installer NIF."}),
            StructField("falcon_fld_max_discount_units", StringType(), True, {"comment": "Falcon max discount units."}),
            StructField("falcon_fld_max_discount", DoubleType(), True, {"comment": "Falcon max discount value."}),
        StructField("falcon_fld_num_year_contract", DoubleType(), True, {"comment": "Falcon number of contract years."}),
            StructField("falcon_fld_psva", BooleanType(), True, {"comment": "Falcon PSVA flag."}),
        StructField("falcon_fld_proposed_change_date", TimestampType(), True, {"comment": "Falcon proposed change date."}),
        StructField("falcon_fld_regenerate_forecast_tacit", BooleanType(), True, {"comment": "Falcon regenerate forecast tacit flag."}),
        StructField("falcon_fld_regenerate_forecast_tariff", BooleanType(), True, {"comment": "Falcon regenerate forecast tariff flag."}),
            StructField("falcon_fld_settlement_axcx", StringType(), True, {"comment": "Falcon settlement AXCX code."}),
            StructField("falcon_fld_supply_tension_apm", StringType(), True, {"comment": "Falcon supply tension APM."}),
            StructField("falcon_fld_supply_tension_cie", StringType(), True, {"comment": "Falcon supply tension CIE."}),
            StructField("falcon_fld_supply_type", StringType(), True, {"comment": "Falcon supply type."}),
        StructField("falcon_fld_total_efficiency_fee", DoubleType(), True, {"comment": "Falcon total efficiency fee."}),
            StructField("falcon_fld_type_discount", StringType(), True, {"comment": "Falcon type discount."}),
        StructField("falcon_fld_type_of_contract_atr", StringType(), True, {"comment": "Falcon type of contract ATR."}),
        StructField("falcon_fld_uninterruptible_power", DoubleType(), True, {"comment": "Falcon uninterruptible power."}),
            StructField("falcon_fld_unit_discount", StringType(), True, {"comment": "Falcon unit discount."}),
            StructField("falcon_fld_validity_cie", StringType(), True, {"comment": "Falcon validity CIE code."}),
            StructField("falcon_fld_case_ct", StringType(), True, {"comment": "Falcon case CT code."}),
            StructField("falcon_fld_discount", DoubleType(), True, {"comment": "Falcon discount value."}),
            StructField("falcon_fld_notify_dist", BooleanType(), True, {"comment": "Falcon notify distribution flag."}),
            StructField("falcon_fld_trade_fee", StringType(), True, {"comment": "Falcon trade fee reference."}),
        StructField("falcon_fld_type_change_date", StringType(), True, {"comment": "Falcon type change date."}),
        StructField("falcon_fld_status_date_last_change", TimestampType(), True, {"comment": "Falcon status last change date."}),
        StructField("falcon_fld_green_product_migrated", BooleanType(), True, {"comment": "Falcon green product migrated flag."}),
            StructField("falcon_fld_discount_aux", DoubleType(), True, {"comment": "Falcon discount auxiliary value."}),
        StructField("falcon_fld_counter_plant_satellite", BooleanType(), True, {"comment": "Falcon counter plant satellite flag."}),
        StructField("falcon_fld_campaign_migrated", BooleanType(), True, {"comment": "Falcon campaign migrated flag."}),
            StructField("falcon_fld_id_aggregation", StringType(), True, {"comment": "Falcon aggregation ID."}),
        StructField("falcon_fld_unit_discount_aux", StringType(), True, {"comment": "Falcon unit discount auxiliary."}),
        StructField("falcon_fld_contract_document", BooleanType(), True, {"comment": "Falcon contract document flag."}),
            StructField("falcon_fld_update_contract", BooleanType(), True, {"comment": "Falcon update contract flag."}),
        StructField("falcon_fld_description_error_update_td", StringType(), True, {"comment": "Falcon description error update TD."}),
            StructField("falcon_fld_error_update_td", BooleanType(), True, {"comment": "Falcon error update TD flag."}),
            StructField("falcon_fld_updated_td", BooleanType(), True, {"comment": "Falcon updated TD flag."}),
        StructField("falcon_fld_commission_payment_type", StringType(), True, {"comment": "Falcon commission payment type."}),
        StructField("falcon_fld_is_quote_auto_renew", BooleanType(), True, {"comment": "Falcon is quote auto renew flag."}),
        StructField("falcon_fld_no_visible_agency", BooleanType(), True, {"comment": "Falcon no visible agency flag."}),
        StructField("falcon_fld_energy_efficiency_financing", StringType(), True, {"comment": "Falcon energy efficiency financing."}),
            StructField("falcon_fld_kam_axpo", StringType(), True, {"comment": "Falcon KAM AXPO."}),
            StructField("falcon_fld_no_permanence", BooleanType(), True, {"comment": "Falcon no permanence flag."}),
        StructField("falcon_fld_commission_by_invoice", BooleanType(), True, {"comment": "Falcon commission by invoice flag."}),
        StructField("falcon_fld_lp", BooleanType(), True, {"comment": "Falcon LP flag."}),
        StructField("falcon_fld_documentation_receipt_date", TimestampType(), True, {"comment": "Falcon documentation receipt date."}),
        StructField("falcon_fld_annual_p1_kwh", DoubleType(), True, {"comment": "Falcon annual energy consumption P1 (kWh)."}),
        StructField("falcon_fld_annual_p2_kwh", DoubleType(), True, {"comment": "Falcon annual energy consumption P2 (kWh)."}),
        StructField("falcon_fld_annual_p3_kwh", DoubleType(), True, {"comment": "Falcon annual energy consumption P3 (kWh)."}),
        StructField("falcon_fld_annual_p4_kwh", DoubleType(), True, {"comment": "Falcon annual energy consumption P4 (kWh)."}),
        StructField("falcon_fld_annual_p5_kwh", DoubleType(), True, {"comment": "Falcon annual energy consumption P5 (kWh)."}),
        StructField("falcon_fld_annual_p6_kwh", DoubleType(), True, {"comment": "Falcon annual energy consumption P6 (kWh)."}),
        StructField("falcon_fld_annual_consumption_signed", DoubleType(), True, {"comment": "Falcon annual consumption signed (kWh)."}),
        neuron_common.SrcCreatedByColumn.to_struct_field(),
        neuron_common.SrcCreatedAtColumn.to_struct_field(),
        standard_columns.LicenseColumn.to_struct_field(),
    ]),
    comment="Salesforce contract data for electricity and energy products (silver layer).",
    sources=(TableIdentifier(catalog="bronze", schema="neuron", name="salesforce_rep_contract"),),
    primary_keys=("id",),
    tags={
        **neuron_common.NEURON_COMMON_TAGS,
        DataDomain.KEY: DataDomain.COUNTERPARTY,
    },
)
