from pyspark.sql.types import (
    BooleanType,
    DateType,
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

from data_platform.data_model import StaticTableModel, TableIdentifier

contractexportsview = StaticTableModel(
    identifier=TableIdentifier(
        catalog="bronze",
        schema="elviz_no",
        name="contractexportsview",
    ),
    schema=StructType(
        [
            StructField("ContractExportId", IntegerType(), True),
            StructField("ContractId", IntegerType(), True),
            StructField("AuctionType", StringType(), True),
            StructField("Audited", BooleanType(), True),
            StructField("Authorized", BooleanType(), True),
            StructField("BalanceArea", StringType(), True),
            StructField("BaseCurrency", StringType(), True),
            StructField("BrokerCompanyExternalId", StringType(), True),
            StructField("BrokerCompanyExportId", IntegerType(), True),
            StructField("BrokerCompanyId", IntegerType(), True),
            StructField("BrokerCompanyName", StringType(), True),
            StructField("BrokerFeeFixed", DoubleType(), True),
            StructField("BrokerFeeFixedUnit", StringType(), True),
            StructField("BrokerFeeVariable", DoubleType(), True),
            StructField("BrokerFeeVariableUnit", StringType(), True),
            StructField("ProductionFacilityCountry", StringType(), True),
            StructField("BuyerInitiatorAggressor", StringType(), True),
            StructField("BuySell", StringType(), True),
            StructField("CapacityId", StringType(), True),
            StructField("CapacityBidPrice", DoubleType(), True),
            StructField("CapacityBidVolume", DoubleType(), True),
            StructField("CapacityTradedVolume", DoubleType(), True),
            StructField("CapFloorPricingResolution", StringType(), True),
            StructField("CashFlowPaidReceived", StringType(), True),
            StructField("CertificateType", StringType(), True),
            StructField("ClearingFeeFixed", DoubleType(), True),
            StructField("ClearingFeeFixedUnit", StringType(), True),
            StructField("ClearingFeeVariable", DoubleType(), True),
            StructField("ClearingFeeVariableUnit", StringType(), True),
            StructField("ClearingType", StringType(), True),
            StructField("Comment", StringType(), True),
            StructField("CommissionFeeFixed", DoubleType(), True),
            StructField("CommissionFeeFixedUnit", StringType(), True),
            StructField("CommissionFeeVariable", DoubleType(), True),
            StructField("CommissionFeeVariableUnit", StringType(), True),
            StructField("Commodity", StringType(), True),
            StructField("CompanyExternalId", StringType(), True),
            StructField("CompanyExportId", IntegerType(), True),
            StructField("CompanyId", IntegerType(), True),
            StructField("CompanyName", StringType(), True),
            StructField("ConfirmedByBroker", BooleanType(), True),
            StructField("ConfirmedByCounterparty", BooleanType(), True),
            StructField("ContractModelType", StringType(), True),
            StructField("ContractPriceType", StringType(), True),
            StructField("ContractTimeZone", StringType(), True),
            StructField("ContractValue", DoubleType(), True),
            StructField("CounterpartyCompanyExternalId", StringType(), True),
            StructField("CounterpartyCompanyExportId", IntegerType(), True),
            StructField("CounterpartyCompanyId", IntegerType(), True),
            StructField("CounterpartyCompanyName", StringType(), True),
            StructField("CounterpartyPortfolioExternalId", StringType(), True),
            StructField("CounterpartyPortfolioExportId", IntegerType(), True),
            StructField("CounterpartyPortfolioId", IntegerType(), True),
            StructField("CounterpartyPortfolioName", StringType(), True),
            StructField("CrossCurrency", StringType(), True),
            StructField("Currency", StringType(), True),
            StructField("CurrencySource", StringType(), True),
            StructField("DealCompression", BooleanType(), True),
            StructField("Deliveries", IntegerType(), True),
            StructField("DeliveryLocation", StringType(), True),
            StructField("DistributedQuantity", DoubleType(), True),
            StructField("EMIRStatus", StringType(), True),
            StructField("EnergySource", StringType(), True),
            StructField("EntryFeeFixed", DoubleType(), True),
            StructField("EntryFeeFixedUnit", StringType(), True),
            StructField("EntryFeeVariable", DoubleType(), True),
            StructField("EntryFeeVariableUnit", StringType(), True),
            StructField("EnvironmentLabel", StringType(), True),
            StructField("ExecutionVenue", StringType(), True),
            StructField("ExitFeeFixed", DoubleType(), True),
            StructField("ExitFeeFixedUnit", StringType(), True),
            StructField("ExitFeeVariable", DoubleType(), True),
            StructField("ExitFeeVariableUnit", StringType(), True),
            StructField("ExpiryDate", TimestampType(), True),
            StructField("ExternalId", StringType(), True),
            StructField("ExternalSource", StringType(), True),
            StructField("FromCountry", StringType(), True),
            StructField("FromDate", TimestampType(), True),
            StructField("GroupField1", StringType(), True),
            StructField("GroupField2", StringType(), True),
            StructField("GroupField3", StringType(), True),
            StructField("HistoricContractPriceSeries", StringType(), True),
            StructField("HistoricMarketPriceSeries", StringType(), True),
            StructField("IndexName", StringType(), True),
            StructField("InitialPrice", DoubleType(), True),
            StructField("InstrumentName", StringType(), True),
            StructField("InstrumentType", StringType(), True),
            StructField("Interconnector", StringType(), True),
            StructField("IsOriginator", BooleanType(), True),
            StructField("LastUpdatedTimeUTC", TimestampType(), True),
            StructField("LoadProfile", StringType(), True),
            StructField("LowerStrike", DoubleType(), True),
            StructField("MarketPriceMultiplier", DoubleType(), True),
            StructField("MasterAgreement", StringType(), True),
            StructField("MaxVolume", DoubleType(), True),
            StructField("MinVolume", DoubleType(), True),
            StructField("OriginalQuantity", DoubleType(), True),
            StructField("Paid", BooleanType(), True),
            StructField("PortfolioExternalId", StringType(), True),
            StructField("PortfolioExportId", IntegerType(), True),
            StructField("PortfolioId", IntegerType(), True),
            StructField("PortfolioName", StringType(), True),
            StructField("Price", DoubleType(), True),
            StructField("PriceBasis", StringType(), True),
            StructField("PriceVolumeUnit", StringType(), True),
            StructField("Priority", StringType(), True),
            StructField("ProductionFacility", StringType(), True),
            StructField("PutCall", StringType(), True),
            StructField("Quantity", DoubleType(), True),
            StructField("QuantityDependencyReferenceContractExportId", IntegerType(), True),
            StructField("QuantityDependencyReferenceContractId", IntegerType(), True),
            StructField("QuantityDependencyReferenceExternalId", StringType(), True),
            StructField("QuantityUnit", StringType(), True),
            StructField("QuotaRegion", StringType(), True),
            StructField("ReferringExportId", IntegerType(), True),
            StructField("RemitReporting", BooleanType(), True),
            StructField("ReplicationId", StringType(), True),
            StructField("Resolution", StringType(), True),
            StructField("RiskValue", DoubleType(), True),
            StructField("SamplingFromDate", TimestampType(), True),
            StructField("SamplingPeriod", StringType(), True),
            StructField("SamplingToDate", TimestampType(), True),
            StructField("SellerInitiatorAggressor", StringType(), True),
            StructField("SettlementRule", StringType(), True),
            StructField("SettlementType", StringType(), True),
            StructField("Status", StringType(), True),
            StructField("Strike", DoubleType(), True),
            StructField("StrikeCurrency", StringType(), True),
            StructField("StripExpiryOffset", IntegerType(), True),
            StructField("StripExpiryTimeOfDay", TimestampType(), True),
            StructField("TerminationDate", DateType(), True),
            StructField("TicketNumber", StringType(), True),
            StructField("TimeStampAuthorisedTransactionUTC", TimestampType(), True),
            StructField("TimeStampClearedUtc", TimestampType(), True),
            StructField("TimeStampConfirmationBrokerUtc", TimestampType(), True),
            StructField("TimeStampConfirmationCounterPartyUtc", TimestampType(), True),
            StructField("TimeStampCounterPartyDealAuthorisedUTC", TimestampType(), True),
            StructField("TimeStampAuthorisedDealUTC", TimestampType(), True),
            StructField("ToCountry", StringType(), True),
            StructField("ToDate", TimestampType(), True),
            StructField("ToPriceBasis", StringType(), True),
            StructField("TotalVolume", DoubleType(), True),
            StructField("TotalVolumeUnit", StringType(), True),
            StructField("UserName", StringType(), True),
            StructField("TradeDate", TimestampType(), True),
            StructField("TradeDateTime", TimestampType(), True),
            StructField("TradeDateTimeUtc", TimestampType(), True),
            StructField("Trader", StringType(), True),
            StructField("TradingFeeFixed", DoubleType(), True),
            StructField("TradingFeeFixedUnit", StringType(), True),
            StructField("TradingFeeVariable", DoubleType(), True),
            StructField("TradingFeeVariableUnit", StringType(), True),
            StructField("TransferDate", TimestampType(), True),
            StructField("UnderlyingInstrumentType", StringType(), True),
            StructField("UnderlyingSettlementType", StringType(), True),
            StructField("UnderlyingVenue", StringType(), True),
            StructField("UpperStrike", DoubleType(), True),
            StructField("UserSpecifiedDealName", StringType(), True),
            StructField("UTI", StringType(), True),
            StructField("CounterpartyTrader", StringType(), True),
            StructField("ReferencePriceSeries", StringType(), True),
            StructField("DestinationReferencePriceSeries", StringType(), True),
            StructField("PortfolioParentId", IntegerType(), True),
            StructField("PortfolioParentName", StringType(), True),
            StructField("CounterpartyPortfolioParentId", IntegerType(), True),
            StructField("CounterpartyPortfolioParentName", StringType(), True),
            StructField("LossFactor", DoubleType(), True),
            StructField("CustomCompanyId", StringType(), True),
            StructField("CustomCompanyName", StringType(), True),
            StructField("Technology", StringType(), True),
            StructField("ForecastProfile", StringType(), True),
            StructField("ProductionLocation", StringType(), True),
            StructField("AuthorisedTransaction", BooleanType(), True),
            StructField("AuthorisedDeal", BooleanType(), True),
            StructField("AuthorisedTransactionBy", StringType(), True),
            StructField("AuthorisedDealBy", StringType(), True),
            StructField("AuditedBy", StringType(), True),
            StructField("TimeStampAuditedUTC", TimestampType(), True),
            StructField("license", StringType(), True),
        ]
    ),
    comment="This table is a reproduction of the ContractExportsView from the Elviz Nordics database.",
    sources=(TableIdentifier(catalog="axpots_elviz_nordics", schema="dbo", name="contractexportsview"),),
    primary_keys=("ContractExportId",),
    tags={
        "Confidentiality Level": "C2_Internal",
        "Personal sensitive information": "No PII",
        "Source System": "elviz_no",
        "Data Owner": "Per Siversen",
    },
)
